// Generated by lsc from reconcile.rules.ts

datatype Option<T> = None | Some(value: T)

datatype LeasePhase = running | ended

datatype LeaseEndReason = released | failed | revoked | expired | abandoned

datatype Source = message | closed

datatype Ending = revoked | expired | stays

datatype OpenExchange = OpenExchange(owner: string, from: int)

datatype CloseRef = CloseRef(owner: string, from: int, through: int)

datatype LiveLease = LiveLease(source: Source, seat: string, phase: LeasePhase, expiresAt: int)

datatype OwedActivation = OwedActivation(source: Source, seat: string)

function expired(expiry: int, now: int): bool
{
  (expiry <= now)
}

lemma expired_ensures(expiry: int, now: int)
  ensures (expired(expiry, now) <==> (expiry <= now))
{
}

function mayEnd(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool): bool
{
  match known {
    case Some(i_known_val) =>
      if (i_known_val.ended? || reason.abandoned?) then
        false
      else
        (reason.revoked? || (pastExpiry == reason.expired?))
    case None =>
      (reason.revoked? || reason.abandoned?)
  }
}

lemma mayEnd_ensures(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool)
  ensures ((match known { case Some(i_) => false case None => true }) ==> (mayEnd(known, reason, pastExpiry) <==> (reason.revoked? || reason.abandoned?)))
  ensures (match known { case Some(i_known_val) => (i_known_val.ended? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.abandoned? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.revoked? ==> mayEnd(known, reason, pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.expired? ==> (mayEnd(known, reason, pastExpiry) <==> pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.released? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.failed? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
{
}

function admitsClose(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool): bool
{
  match open {
    case Some(i_open_val) =>
      ((((i_open_val.from == close.from) && (i_open_val.owner == close.owner)) && (close.through == lastSeq)) && !(exchangeLive))
    case None =>
      false
  }
}

lemma admitsClose_ensures(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool)
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> (match open { case Some(i_) => true case None => false }))
  ensures (match open { case Some(i_open_val) => (admitsClose(open, close, lastSeq, exchangeLive) <==> ((((i_open_val.from == close.from) && (i_open_val.owner == close.owner)) && (close.through == lastSeq)) && !(exchangeLive))) case None => true })
  ensures (exchangeLive ==> !(admitsClose(open, close, lastSeq, exchangeLive)))
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> (close.through == lastSeq))
{
}

function readyToSend(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): bool
  requires (resend >= 0)
{
  var backoffOver := (!(backedOff) || (notBefore <= now));
  var windowOver := (!(wasSent) || ((sentAt + resend) <= now));
  (backoffOver && windowOver)
}

lemma readyToSend_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 0)
  ensures (readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend) <==> ((!(backedOff) || (notBefore <= now)) && (!(wasSent) || ((sentAt + resend) <= now))))
  ensures (backedOff ==> (notBefore > now) ==> !(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)))
  ensures (wasSent ==> (now < (sentAt + resend)) ==> !(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)))
{
}

function waitsUntil(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): int
  requires (resend >= 0)
{
  var backoff := (if backedOff then notBefore else now);
  if (backoff > now) then
    backoff
  else
    if wasSent then
      (sentAt + resend)
    else
      now
}

lemma waitsUntil_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 0)
  ensures ((waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) <= now) <==> readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend))
  ensures (backedOff ==> (notBefore > now) ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == notBefore))
  ensures ((!(backedOff) || (notBefore <= now)) ==> wasSent ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == (sentAt + resend)))
  ensures ((!(backedOff) || (notBefore <= now)) ==> !(wasSent) ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == now))
{
}

function looksAgainAt(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): int
  requires (resend >= 1)
{
  var at := waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend);
  if (at > now) then
    at
  else
    (now + resend)
}

lemma looksAgainAt_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 1)
  ensures (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) > now)
  ensures (!(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)) ==> (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) == waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend)))
  ensures (readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend) ==> (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) == (now + resend)))
{
}

function earliestAfter(now: int, times: seq<int>): Option<int>
  decreases |times|
{
  if (|times| == 0) then
    None
  else
    var head := (if ((0 <= 0) && (0 < |times|)) then times[0] else now);
    var rest := earliestAfter(now, times[1..]);
    if (head <= now) then
      rest
    else
      match rest {
        case Some(i_rest_val) =>
          Some((if (head < i_rest_val) then head else i_rest_val))
        case None =>
          Some(head)
      }
}

lemma earliestAfter_ensures(now: int, times: seq<int>)
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => (i_result_val > now) case None => true })
  ensures ((match earliestAfter(now, times) { case Some(i_) => false case None => true }) <==> forall i: int :: ((0 <= i) ==> (i < |times|) ==> (times[i] <= now)))
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => forall i: int :: ((0 <= i) ==> (i < |times|) ==> (times[i] > now) ==> (i_result_val <= times[i])) case None => true })
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => exists i: int :: (((0 <= i) && (i < |times|)) && (times[i] == i_result_val)) case None => true })
{
}

function removedAfter(removalSeq: int, position: int): bool
{
  (removalSeq > position)
}

lemma removedAfter_ensures(removalSeq: int, position: int)
  ensures (removedAfter(removalSeq, position) <==> (removalSeq > position))
{
}

function staleLease(derived: bool, seated: bool, removedAfterCause: bool): bool
{
  ((!(derived) || !(seated)) || removedAfterCause)
}

lemma staleLease_ensures(derived: bool, seated: bool, removedAfterCause: bool)
  ensures (staleLease(derived, seated, removedAfterCause) <==> ((!(derived) || !(seated)) || removedAfterCause))
  ensures (derived ==> seated ==> !(removedAfterCause) ==> !(staleLease(derived, seated, removedAfterCause)))
{
}

function endingOf(running: bool, stale: bool, pastExpiry: bool): Ending
{
  if !(running) then
    Ending.stays
  else
    if stale then
      Ending.revoked
    else
      if pastExpiry then
        Ending.expired
      else
        Ending.stays
}

lemma endingOf_ensures(running: bool, stale: bool, pastExpiry: bool)
  ensures (!(running) ==> endingOf(running, stale, pastExpiry).stays?)
  ensures (running ==> stale ==> endingOf(running, stale, pastExpiry).revoked?)
  ensures (running ==> !(stale) ==> pastExpiry ==> endingOf(running, stale, pastExpiry).expired?)
  ensures (running ==> !(stale) ==> !(pastExpiry) ==> endingOf(running, stale, pastExpiry).stays?)
  ensures (endingOf(running, stale, pastExpiry).expired? ==> !(stale))
  ensures ((!endingOf(running, stale, pastExpiry).stays?) ==> running)
{
}

function mayClose(stopped: bool, endings: int, exchangeOpen: bool, exchangeLive: bool): bool
  requires (endings >= 0)
{
  (((!(stopped) && (endings == 0)) && exchangeOpen) && !(exchangeLive))
}

lemma mayClose_ensures(stopped: bool, endings: int, exchangeOpen: bool, exchangeLive: bool)
  requires (endings >= 0)
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> !(stopped))
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> (endings == 0))
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> exchangeOpen)
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> !(exchangeLive))
  ensures (!(stopped) ==> (endings == 0) ==> exchangeOpen ==> !(exchangeLive) ==> mayClose(stopped, endings, exchangeOpen, exchangeLive))
{
}

function closeMoved(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool): bool
{
  match open {
    case Some(i_open_val) =>
      ((i_open_val.from == close.from) && ((lastSeq != close.through) || exchangeLive))
    case None =>
      false
  }
}

lemma closeMoved_ensures(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool)
  ensures (closeMoved(open, close, lastSeq, exchangeLive) ==> (match open { case Some(i_) => true case None => false }))
  ensures (match open { case Some(i_open_val) => (closeMoved(open, close, lastSeq, exchangeLive) <==> ((i_open_val.from == close.from) && ((lastSeq != close.through) || exchangeLive))) case None => true })
  ensures (closeMoved(open, close, lastSeq, exchangeLive) ==> !(admitsClose(open, close, lastSeq, exchangeLive)))
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> !(closeMoved(open, close, lastSeq, exchangeLive)))
{
}

function namesWriter(configured: bool, seated: bool): bool
{
  (configured && seated)
}

lemma namesWriter_ensures(configured: bool, seated: bool)
  ensures (namesWriter(configured, seated) ==> configured)
  ensures (namesWriter(configured, seated) ==> seated)
  ensures (configured ==> seated ==> namesWriter(configured, seated))
{
}

function stillExpired(expiry: int, now: int, later: int): bool
  requires (now <= later)
{
  expired(expiry, later)
}

lemma stillExpired_ensures(expiry: int, now: int, later: int)
  requires (now <= later)
  ensures (expired(expiry, now) ==> stillExpired(expiry, now, later))
  ensures (stillExpired(expiry, now, later) <==> expired(expiry, later))
{
}

function endingStands(stale: bool, expiry: int, now: int, later: int): bool
  requires (now <= later)
{
  var ending := endingOf(true, stale, expired(expiry, now));
  if ending.expired? then
    mayEnd(Some(LeasePhase.running), LeaseEndReason.expired, stillExpired(expiry, now, later))
  else
    (ending.revoked? && mayEnd(Some(LeasePhase.running), LeaseEndReason.revoked, expired(expiry, later)))
}

lemma endingStands_ensures(stale: bool, expiry: int, now: int, later: int)
  requires (now <= later)
  ensures (endingOf(true, stale, expired(expiry, now)).expired? ==> mayEnd(Some(LeasePhase.running), LeaseEndReason.expired, expired(expiry, later)))
  ensures (endingOf(true, stale, expired(expiry, now)).revoked? ==> mayEnd(Some(LeasePhase.running), LeaseEndReason.revoked, expired(expiry, later)))
  ensures (endingStands(stale, expiry, now, later) <==> (!endingOf(true, stale, expired(expiry, now)).stays?))
{
}

function answers(running: bool, reason: LeaseEndReason, atCause: bool, readThrough: int, seq_: int): bool
  requires (readThrough >= 0)
  requires (seq_ >= 1)
{
  (running || (((reason.abandoned? || reason.revoked?) && atCause) || (if (reason.failed? || reason.expired?) then false else (readThrough >= seq_))))
}

lemma answers_ensures(running: bool, reason: LeaseEndReason, atCause: bool, readThrough: int, seq_: int)
  requires (readThrough >= 0)
  requires (seq_ >= 1)
  ensures (running ==> answers(running, reason, atCause, readThrough, seq_))
  ensures (!(running) ==> (reason.abandoned? || reason.revoked?) ==> atCause ==> answers(running, reason, atCause, readThrough, seq_))
  ensures (!(running) ==> (reason.failed? || reason.expired?) ==> !(answers(running, reason, atCause, readThrough, seq_)))
  ensures (!(running) ==> reason.released? ==> (answers(running, reason, atCause, readThrough, seq_) <==> (readThrough >= seq_)))
  ensures (!(running) ==> (reason.abandoned? || reason.revoked?) ==> !(atCause) ==> (answers(running, reason, atCause, readThrough, seq_) <==> (readThrough >= seq_)))
  ensures (!(running) ==> !(atCause) ==> (readThrough < seq_) ==> !(answers(running, reason, atCause, readThrough, seq_)))
{
}

function liveNow(phase: LeasePhase, expiresAt: int, now: int): bool
{
  (phase.running? && !(expired(expiresAt, now)))
}

lemma liveNow_ensures(phase: LeasePhase, expiresAt: int, now: int)
  ensures (liveNow(phase, expiresAt, now) <==> (phase.running? && !(expired(expiresAt, now))))
  ensures (phase.ended? ==> !(liveNow(phase, expiresAt, now)))
  ensures (phase.running? ==> (liveNow(phase, expiresAt, now) <==> (now < expiresAt)))
{
}

function holdsExchange(source: Source): bool
{
  source.message?
}

lemma holdsExchange_ensures(source: Source)
  ensures (holdsExchange(source) <==> source.message?)
{
}

function exchangeLive(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int): bool
{
  ((exists lease :: lease in leases && (liveNow(lease.phase, lease.expiresAt, now) && holdsExchange(lease.source))) || (exists owed :: owed in due && holdsExchange(owed.source)))
}

lemma exchangeLive_ensures(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int)
  ensures (exchangeLive(leases, due, now) <==> ((exists i: int :: ((((0 <= i) && (i < |leases|)) && liveNow(leases[i].phase, leases[i].expiresAt, now)) && holdsExchange(leases[i].source))) || exists j: int :: (((0 <= j) && (j < |due|)) && holdsExchange(due[j].source))))
  ensures ((forall i: int :: ((0 <= i) ==> (i < |leases|) ==> leases[i].source.closed?)) ==> (forall j: int :: ((0 <= j) ==> (j < |due|) ==> due[j].source.closed?)) ==> !(exchangeLive(leases, due, now)))
  ensures ((exists j: int :: (((0 <= j) && (j < |due|)) && due[j].source.message?)) ==> exchangeLive(leases, due, now))
  ensures ((forall i: int :: ((0 <= i) ==> (i < |leases|) ==> !(liveNow(leases[i].phase, leases[i].expiresAt, now)))) ==> (|due| == 0) ==> !(exchangeLive(leases, due, now)))
  ensures ((|leases| == 0) ==> (|due| == 0) ==> !(exchangeLive(leases, due, now)))
{
}

function seatLive(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int, seat: string): bool
{
  ((exists lease :: lease in leases && ((lease.seat == seat) && liveNow(lease.phase, lease.expiresAt, now))) || (exists owed :: owed in due && (owed.seat == seat)))
}

lemma seatLive_ensures(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int, seat: string)
  ensures (seatLive(leases, due, now, seat) <==> ((exists i: int :: ((((0 <= i) && (i < |leases|)) && (leases[i].seat == seat)) && liveNow(leases[i].phase, leases[i].expiresAt, now))) || exists j: int :: (((0 <= j) && (j < |due|)) && (due[j].seat == seat))))
  ensures ((|leases| == 0) ==> (|due| == 0) ==> !(seatLive(leases, due, now, seat)))
{
}

method forgets(sentIds: seq<string>, dueIds: seq<string>) returns (res: seq<string>)
  ensures (|res| <= |sentIds|)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> !((res[i] in dueIds)))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in sentIds))
  ensures forall i: int :: ((0 <= i) ==> (i < |sentIds|) ==> !((sentIds[i] in dueIds)) ==> (sentIds[i] in res))
  ensures forall i: int :: ((0 <= i) ==> (i < |dueIds|) ==> !((dueIds[i] in res)))
{
  var out: seq<string> := [];
  var i := 0;
  while (i < |sentIds|)
    invariant (0 <= i)
    invariant (i <= |sentIds|)
    invariant (|out| <= i)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> !((out[k] in dueIds)))
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] in sentIds))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> !((sentIds[k] in dueIds)) ==> (sentIds[k] in out))
    decreases (|sentIds| - i)
  {
    var id := (if ((0 <= i) && (i < |sentIds|)) then sentIds[i] else "");
    if !((id in dueIds)) {
      out := (out + [id]);
    }
    i := (i + 1);
  }
  return out;
}
