/**
 * The documents checked in under `drive/`, as one record of path to text.
 *
 * `scripts/drive-seed.mjs` writes this file. Do not edit it: edit `drive/`
 * and run `pnpm seed`. The room seeds its workspace from here, so it reads
 * no file at run time and runs on a host with no disk.
 */
export const DRIVE_SEED: Record<string, string> = {
	'/site/README.md':
		'# Kestrel Yard, Block C — the site drive\n\nThe shared drive for Block C. Every product on the site reads it, and every\nproduct writes to the diary. State that a product owns (tasks, deliveries,\nhours) lives in that product, not here. This drive holds the documents the\nsite works to.\n\n| Path                                    | What                                                | Written by                          |\n| --------------------------------------- | --------------------------------------------------- | ----------------------------------- |\n| `/site/pour-plan/level-3-slab.md`       | The method statement for the Level 3 slab pour      | The temporary works coordinator     |\n| `/site/weather/week-35.md`              | The forecast for the week, issued each morning      | The site office                     |\n| `/site/inspections/building-control.md` | How building control inspections are booked         | The site office                     |\n| `/site/diary/YYYY-MM-DD.md`             | The site diary: one file per day, decisions and why | Every product, one entry per change |\n\nDiary entries are appended, never rewritten. An entry is one line: the time,\nwho wrote it, and what changed.\n',
	'/site/diary/2026-08-24.md':
		'# Site diary, Mon 24 Aug\n\n- 07:10 sam — Deck open, 13 on site. Formwork Level 3 at 80%, striking crew on falsework.\n- 09:30 materials-tracker — 16 mm rebar 4.2 t on site against 11.7 t needed. D-4471 (7.5 t, Hadley Steel) confirmed for Wed 26 Aug 14:00.\n- 11:00 task-management — T-121 pre-pour inspection not booked: fixing cannot finish before the rebar lands. T-118 stays blocked on T-121 and T-130.\n- 15:45 priya — Client asked for a pour date. Told them Thursday is the plan, to confirm Tuesday.\n- 16:30 time-tracker — Formwork at 44 h this week, one below the overtime threshold.\n',
	'/site/inspections/building-control.md':
		'# Building control inspections\n\nInspector: Elmbridge Building Control, duty inspector line 01372 000 000.\nBookings are made by the project manager only.\n\n## How a slot is booked\n\n- Notice: 48 hours, counted in working hours. A booking made after 13:00 on\n  a Tuesday gets Thursday 13:00 at the earliest.\n- Slots: 08:00 or 13:00, Monday to Friday. Building control does not\n  inspect at weekends.\n- A pre-pour inspection needs the rebar fixed and the formwork closed. An\n  inspector who finds fixing still in progress leaves and the slot is lost.\n\n## What this means for a slab pour\n\n- A weekday pour needs the inspection the day before, at 13:00 at the\n  latest.\n- A Saturday pour needs the inspection on the Friday. Book the Friday 13:00\n  slot by Wednesday 13:00.\n- The inspector signs the pour card. The card stays in the site office.\n\n## Log\n\n| Date       | Inspection       | Result                          |\n| ---------- | ---------------- | ------------------------------- |\n| Wed 12 Aug | Level 2 pre-pour | Passed, pour card signed        |\n| Mon 24 Aug | Level 3 pre-pour | Not booked: fixing not complete |\n',
	'/site/pour-plan/level-3-slab.md':
		"# Method statement: Level 3 slab pour (T-118)\n\nRevision C, issued Fri 21 Aug. Temporary works coordinator: R. Okafor.\n\n## The pour\n\n- Concrete: C32/40, 96 m³, from Trent Ready-Mix. The order locks 24 hours\n  before the slot; a cancellation inside the lock is charged.\n- Placement: by pump from Bay 2. One pump, one operator holding a pump\n  operation ticket. Groundworks holds that ticket on this project.\n- Window: 07:00 to 13:00. The last load is on site by 11:30 so the finishing\n  crew has two hours before the surface goes off.\n- Rate: 16 m³ per hour, one load every 20 minutes.\n\n## People on the day\n\n| Role                | Trade        | Number | Ticket needed      |\n| ------------------- | ------------ | ------ | ------------------ |\n| Pour supervisor     | Concrete     | 1      | pour supervision   |\n| Placing and finish  | Concrete     | 5      | power float (2 of) |\n| Pump operator       | Groundworks  | 1      | pump operation     |\n| Standby steel fixer | Steel fixers | 2      | none               |\n\nNine people on the deck at 07:00. A pour on a Saturday is paid at the\nweekend rate and needs overtime approved by the Friday.\n\n## Before the pour\n\n1. Rebar fixing complete and signed by the foreman (T-126).\n2. Building control pre-pour inspection passed (T-121). No pour without the\n   inspector's signature on the card.\n3. Pump on site the evening before, tested on water (T-130).\n4. Formwork and falsework checked by the temporary works coordinator on the\n   morning of the pour.\n\n## Weather limits\n\n- No pour if the forecast for the window shows more than 2 mm of rain in any\n  hour. Rain on fresh concrete washes out the surface and the finish fails.\n- No pour if the air temperature is below 5 °C at 07:00.\n- Wind above 40 km/h stops the pump boom.\n\nIf the forecast fails these limits on the morning of the pour, the pour\nmoves to the next day that passes them. The concrete order moves with it.\n\n## After the pour\n\nCure for seven days before striking the formwork. Level 2 strike (T-124)\nis independent of this pour and can go ahead.\n",
	'/site/weather/week-35.md':
		"# Forecast, week 35 (w/c Mon 24 Aug)\n\nIssued Tue 25 Aug, 06:00, from the Met Office site feed. Updated each\nmorning by the site office. Hourly rain is the figure the pour plan reads.\n\n| Day        | 07:00–13:00                          | Afternoon                    | Temp at 07:00 | Wind    |\n| ---------- | ------------------------------------ | ---------------------------- | ------------- | ------- |\n| Tue 25 Aug | Dry, overcast                        | Dry                          | 14 °C         | 15 km/h |\n| Wed 26 Aug | Dry until 11:00, then light showers  | Showers, under 1 mm per hour | 13 °C         | 20 km/h |\n| Thu 27 Aug | Rain, 4 to 6 mm per hour until 13:00 | Clearing from 14:00          | 12 °C         | 30 km/h |\n| Fri 28 Aug | Dry, bright                          | Dry                          | 11 °C         | 18 km/h |\n| Sat 29 Aug | Dry, sunny                           | Dry                          | 13 °C         | 10 km/h |\n| Sun 30 Aug | Rain from 09:00, 3 mm per hour       | Rain                         | 12 °C         | 25 km/h |\n\nThursday morning fails the pour plan's rain limit. Friday and Saturday pass\nevery limit. Sunday fails from 09:00.\n",
};
