// Generated by lsc from rules.verified.ts

datatype Option<T> = None | Some(value: T)

function MathMax(a: int, b: int): int { if a >= b then a else b }

datatype StoredEntry = StoredEntry(position: int)

datatype Fence = Fence(fence: Option<string>, fenced: bool, superseded: bool)

datatype Passed = Passed(state: Fence, keep: bool, lost: bool)

datatype Seen = Seen(kind: string, run: Option<string>)

datatype Keyed = fresh_ | replay | conflict

function sameWriter(own: Option<string>, writer: Option<string>): bool
{
  (((match own { case Some(i_) => true case None => false }) && (match writer { case Some(i_) => true case None => false })) && (own == writer))
}

lemma sameWriter_ensures(own: Option<string>, writer: Option<string>)
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(sameWriter(own, writer)))
  ensures ((match writer { case Some(i_) => false case None => true }) ==> !(sameWriter(own, writer)))
  ensures (match own { case Some(i_own_val) => (match writer { case Some(i_writer_val) => (sameWriter(own, writer) <==> (i_own_val == i_writer_val)) case None => true }) case None => true })
{
}

function nextSeq(lastSeq: int): int
  requires (lastSeq >= 0)
  requires (lastSeq < 9007199254740990)
{
  (lastSeq + 1)
}

lemma nextSeq_ensures(lastSeq: int)
  requires (lastSeq >= 0)
  requires (lastSeq < 9007199254740990)
  ensures (nextSeq(lastSeq) == (lastSeq + 1))
  ensures (nextSeq(lastSeq) > lastSeq)
  ensures (nextSeq(lastSeq) <= 9007199254740990)
{
}

function advanceSeq(lastSeq: int, seq_: int): int
  requires (lastSeq >= 0)
  requires (seq_ >= 0)
  requires (lastSeq <= 9007199254740990)
  requires (seq_ <= 9007199254740990)
{
  MathMax(lastSeq, seq_)
}

lemma advanceSeq_ensures(lastSeq: int, seq_: int)
  requires (lastSeq >= 0)
  requires (seq_ >= 0)
  requires (lastSeq <= 9007199254740990)
  requires (seq_ <= 9007199254740990)
  ensures (advanceSeq(lastSeq, seq_) >= lastSeq)
  ensures (advanceSeq(lastSeq, seq_) >= seq_)
  ensures ((advanceSeq(lastSeq, seq_) == lastSeq) || (advanceSeq(lastSeq, seq_) == seq_))
  ensures (advanceSeq(lastSeq, seq_) <= 9007199254740990)
  ensures ((advanceSeq(lastSeq, seq_) < 9007199254740990) ==> (nextSeq(advanceSeq(lastSeq, seq_)) > seq_))
  ensures ((advanceSeq(lastSeq, seq_) < 9007199254740990) ==> (nextSeq(advanceSeq(lastSeq, seq_)) > lastSeq))
{
}

function scanned(cursor: int, position: int): int
  requires (cursor >= 0)
  requires (position >= 0)
{
  MathMax(cursor, position)
}

lemma scanned_ensures(cursor: int, position: int)
  requires (cursor >= 0)
  requires (position >= 0)
  ensures (scanned(cursor, position) >= cursor)
  ensures (scanned(cursor, position) >= position)
  ensures ((scanned(cursor, position) == cursor) || (scanned(cursor, position) == position))
{
}

function nextPosition(head: int): int
{
  (head + 1)
}

lemma nextPosition_ensures(head: int)
  ensures (nextPosition(head) == (head + 1))
  ensures (nextPosition(head) > head)
{
}

function admit(head: int, expected: int): Option<int>
  requires (head >= 0)
{
  if (head == expected) then
    Option.Some(nextPosition(head))
  else
    Option.None
}

lemma admit_ensures(head: int, expected: int)
  requires (head >= 0)
  ensures ((match admit(head, expected) { case Some(i_) => true case None => false }) <==> (head == expected))
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val == nextPosition(head)) case None => true })
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val == (expected + 1)) case None => true })
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val > expected) case None => true })
  ensures ((head != expected) ==> (match admit(head, expected) { case Some(i_) => false case None => true }))
{
}

function readPosition(after: int, scanned: Option<int>): int
{
  match scanned {
    case Some(i_scanned_val) =>
      MathMax(after, i_scanned_val)
    case None =>
      after
  }
}

lemma readPosition_ensures(after: int, scanned: Option<int>)
  ensures (readPosition(after, scanned) >= after)
  ensures (match scanned { case Some(i_scanned_val) => (readPosition(after, scanned) >= i_scanned_val) case None => true })
  ensures ((match scanned { case Some(i_) => false case None => true }) ==> (readPosition(after, scanned) == after))
  ensures (match scanned { case Some(i_scanned_val) => ((i_scanned_val >= after) ==> (readPosition(after, scanned) == i_scanned_val)) case None => true })
  ensures (match scanned { case Some(i_scanned_val) => ((i_scanned_val < after) ==> (readPosition(after, scanned) == after)) case None => true })
{
}

function passFence(state: Fence, own: Option<string>, writer: Option<string>): Passed
{
  if sameWriter(own, writer) then
    Passed(Fence(writer, true, state.superseded), true, false)
  else
    var superseded := (state.superseded || state.fenced);
    Passed(Fence(writer, state.fenced, superseded), true, (superseded && !(state.superseded)))
}

lemma passFence_ensures(state: Fence, own: Option<string>, writer: Option<string>)
  ensures (passFence(state, own, writer).state.fence == writer)
  ensures passFence(state, own, writer).keep
  ensures (sameWriter(own, writer) ==> passFence(state, own, writer).state.fenced)
  ensures (sameWriter(own, writer) ==> (passFence(state, own, writer).state.superseded == state.superseded))
  ensures (!(sameWriter(own, writer)) ==> (passFence(state, own, writer).state.fenced == state.fenced))
  ensures (!(sameWriter(own, writer)) ==> state.fenced ==> passFence(state, own, writer).state.superseded)
  ensures (state.superseded ==> passFence(state, own, writer).state.superseded)
  ensures (state.fenced ==> passFence(state, own, writer).state.fenced)
  ensures (!(state.superseded) ==> !(state.fenced) ==> !(passFence(state, own, writer).state.superseded))
  ensures (passFence(state, own, writer).lost <==> (!(state.superseded) && passFence(state, own, writer).state.superseded))
{
}

function passEntry(state: Fence, writer: Option<string>): Passed
{
  var keep := (((match state.fence { case Some(i_) => false case None => true }) || (match writer { case Some(i_) => false case None => true })) || (writer == state.fence));
  Passed(state, keep, false)
}

lemma passEntry_ensures(state: Fence, writer: Option<string>)
  ensures (passEntry(state, writer).state == state)
  ensures !(passEntry(state, writer).lost)
  ensures ((match state.fence { case Some(i_) => false case None => true }) ==> passEntry(state, writer).keep)
  ensures ((match writer { case Some(i_) => false case None => true }) ==> passEntry(state, writer).keep)
  ensures (match state.fence { case Some(i_state_fence_val) => (match writer { case Some(i_writer_val) => (passEntry(state, writer).keep <==> (i_state_fence_val == i_writer_val)) case None => true }) case None => true })
{
}

function fenceStep(state: Fence, own: Option<string>, isRun: bool, writer: Option<string>): Passed
{
  if isRun then
    passFence(state, own, writer)
  else
    passEntry(state, writer)
}

lemma fenceStep_ensures(state: Fence, own: Option<string>, isRun: bool, writer: Option<string>)
  ensures (state.superseded ==> fenceStep(state, own, isRun, writer).state.superseded)
  ensures (state.fenced ==> fenceStep(state, own, isRun, writer).state.fenced)
  ensures (isRun ==> fenceStep(state, own, isRun, writer).keep)
  ensures (isRun ==> (fenceStep(state, own, isRun, writer).state.fence == writer))
  ensures (!(isRun) ==> (fenceStep(state, own, isRun, writer).state == state))
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (!(isRun) ==> (i_writer_val != i_state_fence_val) ==> !(fenceStep(state, own, isRun, writer).keep)) case None => true }) case None => true })
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (!(isRun) ==> (i_writer_val == i_state_fence_val) ==> fenceStep(state, own, isRun, writer).keep) case None => true }) case None => true })
  ensures (!(isRun) ==> (match state.fence { case Some(i_) => false case None => true }) ==> fenceStep(state, own, isRun, writer).keep)
  ensures (!(isRun) ==> (match writer { case Some(i_) => false case None => true }) ==> fenceStep(state, own, isRun, writer).keep)
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (fenceStep(state, own, isRun, writer).keep ==> !(isRun) ==> (i_writer_val == i_state_fence_val)) case None => true }) case None => true })
  ensures (fenceStep(state, own, isRun, writer).lost ==> isRun)
  ensures (fenceStep(state, own, isRun, writer).lost ==> (!(state.superseded) && fenceStep(state, own, isRun, writer).state.superseded))
  ensures (isRun ==> sameWriter(own, writer) ==> fenceStep(state, own, isRun, writer).state.fenced)
  ensures (isRun ==> sameWriter(own, writer) ==> (fenceStep(state, own, isRun, writer).state.superseded == state.superseded))
  ensures (isRun ==> !(sameWriter(own, writer)) ==> state.fenced ==> fenceStep(state, own, isRun, writer).state.superseded)
  ensures (isRun ==> !(sameWriter(own, writer)) ==> state.fenced ==> !(state.superseded) ==> fenceStep(state, own, isRun, writer).lost)
  ensures (!(state.fenced) ==> !((isRun && sameWriter(own, writer))) ==> (fenceStep(state, own, isRun, writer).state.fenced == false))
  ensures (!(state.fenced) ==> !(state.superseded) ==> !(fenceStep(state, own, isRun, writer).state.superseded))
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(state.fenced) ==> !(fenceStep(state, own, isRun, writer).state.fenced))
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(state.fenced) ==> !(state.superseded) ==> (!(fenceStep(state, own, isRun, writer).state.superseded) && !(fenceStep(state, own, isRun, writer).lost)))
{
}

function keyed(seen: Option<Seen>, kind: string, fenceKind: string, own: Option<string>): Keyed
{
  match seen {
    case Some(i_seen_val) =>
      if (i_seen_val.kind != kind) then
        Keyed.conflict
      else
        if ((kind == fenceKind) && !(sameWriter(own, i_seen_val.run))) then
          Keyed.conflict
        else
          Keyed.replay
    case None =>
      Keyed.fresh_
  }
}

lemma keyed_ensures(seen: Option<Seen>, kind: string, fenceKind: string, own: Option<string>)
  ensures ((match seen { case Some(i_) => false case None => true }) ==> keyed(seen, kind, fenceKind, own).fresh_?)
  ensures (match seen { case Some(i_seen_val) => (!keyed(seen, kind, fenceKind, own).fresh_?) case None => true })
  ensures (keyed(seen, kind, fenceKind, own).fresh_? ==> (match seen { case Some(i_) => false case None => true }))
  ensures ((match seen { case Some(i_) => false case None => true }) ==> (!keyed(seen, kind, fenceKind, own).replay?))
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind != kind) ==> (!keyed(seen, kind, fenceKind, own).replay?)) case None => true })
  ensures ((match seen { case Some(i_) => false case None => true }) ==> (!keyed(seen, kind, fenceKind, own).conflict?))
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind != kind) ==> keyed(seen, kind, fenceKind, own).conflict?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> (kind != fenceKind) ==> keyed(seen, kind, fenceKind, own).replay?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> sameWriter(own, i_seen_val.run) ==> keyed(seen, kind, fenceKind, own).replay?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> (kind == fenceKind) ==> !(sameWriter(own, i_seen_val.run)) ==> keyed(seen, kind, fenceKind, own).conflict?) case None => true })
{
}

function writable(closed: bool, state: Fence, own: Option<string>, isRun: bool): bool
{
  ((!(closed) && !(state.superseded)) && fenceStep(state, own, isRun, own).keep)
}

lemma writable_ensures(closed: bool, state: Fence, own: Option<string>, isRun: bool)
  ensures (closed ==> !(writable(closed, state, own, isRun)))
  ensures (state.superseded ==> !(writable(closed, state, own, isRun)))
  ensures (writable(closed, state, own, isRun) ==> fenceStep(state, own, isRun, own).keep)
  ensures (!(closed) ==> !(state.superseded) ==> fenceStep(state, own, isRun, own).keep ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> isRun ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> (match own { case Some(i_) => false case None => true }) ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> (match state.fence { case Some(i_) => false case None => true }) ==> writable(closed, state, own, isRun))
  ensures (match state.fence { case Some(i_state_fence_val) => (match own { case Some(i_own_val) => (!(closed) ==> !(state.superseded) ==> (i_own_val == i_state_fence_val) ==> writable(closed, state, own, isRun)) case None => true }) case None => true })
  ensures (match own { case Some(i_own_val) => (match state.fence { case Some(i_state_fence_val) => ((i_own_val != i_state_fence_val) ==> !(isRun) ==> !(writable(closed, state, own, isRun))) case None => true }) case None => true })
{
}

method visibleEntries(entries: seq<StoredEntry>, after: int) returns (res: seq<StoredEntry>)
  ensures (|res| <= |entries|)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i].position > after))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in entries))
  ensures forall i: int :: ((0 <= i) ==> (i < |entries|) ==> (entries[i].position > after) ==> (entries[i] in res))
  ensures forall i: int :: ((0 <= i) ==> (i < |entries|) ==> (entries[i].position <= after) ==> !((entries[i] in res)))
{
  var out: seq<StoredEntry> := [];
  var i := 0;
  while (i < |entries|)
    invariant (0 <= i)
    invariant (i <= |entries|)
    invariant (|out| <= i)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k].position > after))
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] in entries))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> (entries[k].position > after) ==> (entries[k] in out))
    decreases (|entries| - i)
  {
    var stored := (if ((0 <= i) && (i < |entries|)) then entries[i] else StoredEntry(after));
    if (stored.position > after) {
      out := (out + [stored]);
    }
    i := (i + 1);
  }
  return out;
}

// ---- Proof additions (hand-written, additions-only) ----------------------

// One stored entry as the fence reads it: whether it is a run entry, and who wrote it.
datatype Stamped = Stamped(isRun: bool, writer: Option<string>)

// The fence over a whole read: fenceStep folded over the stored entries in order.
function fenceFold(state: Fence, own: Option<string>, entries: seq<Stamped>): Fence
  decreases |entries|
{
  if |entries| == 0 then state
  else fenceFold(fenceStep(state, own, entries[0].isRun, entries[0].writer).state, own, entries[1..])
}

// Superseded is absorbing over any read.
lemma SupersededIsAbsorbing(state: Fence, own: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  ensures state.superseded ==> fenceFold(state, own, entries).superseded
{
  if |entries| > 0 {
    var next := fenceStep(state, own, entries[0].isRun, entries[0].writer).state;
    fenceStep_ensures(state, own, entries[0].isRun, entries[0].writer);
    SupersededIsAbsorbing(next, own, entries[1..]);
  }
}

// Fenced is absorbing over any read.
lemma FencedIsAbsorbing(state: Fence, own: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  ensures state.fenced ==> fenceFold(state, own, entries).fenced
{
  if |entries| > 0 {
    var next := fenceStep(state, own, entries[0].isRun, entries[0].writer).state;
    fenceStep_ensures(state, own, entries[0].isRun, entries[0].writer);
    FencedIsAbsorbing(next, own, entries[1..]);
  }
}

// A read that passes no run entry leaves the fence where it stood.
lemma NoRunEntryKeepsFence(state: Fence, own: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  requires forall k :: 0 <= k < |entries| ==> !entries[k].isRun
  ensures fenceFold(state, own, entries) == state
{
  if |entries| > 0 {
    fenceStep_ensures(state, own, entries[0].isRun, entries[0].writer);
    NoRunEntryKeepsFence(state, own, entries[1..]);
  }
}

// Before any run entry, every entry is kept.
lemma BeforeFirstFenceEverythingKept(state: Fence, own: Option<string>, entries: seq<Stamped>, k: int)
  requires state.fence == None
  requires forall j :: 0 <= j < |entries| ==> !entries[j].isRun
  requires 0 <= k < |entries|
  ensures fenceStep(fenceFold(state, own, entries[..k]), own, entries[k].isRun, entries[k].writer).keep
{
  NoRunEntryKeepsFence(state, own, entries[..k]);
  fenceStep_ensures(state, own, entries[k].isRun, entries[k].writer);
}

// A journal that never sees its own run entry is never superseded, whatever the read holds.
lemma NeverFencedNeverSuperseded(state: Fence, own: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  requires !state.fenced && !state.superseded
  requires forall j :: 0 <= j < |entries| ==> !(entries[j].isRun && sameWriter(own, entries[j].writer))
  ensures !fenceFold(state, own, entries).superseded
  ensures !fenceFold(state, own, entries).fenced
{
  if |entries| > 0 {
    var next := fenceStep(state, own, entries[0].isRun, entries[0].writer).state;
    fenceStep_ensures(state, own, entries[0].isRun, entries[0].writer);
    NeverFencedNeverSuperseded(next, own, entries[1..]);
  }
}

// How many steps of a read tell the caller `lost`.
function lostCount(state: Fence, own: Option<string>, entries: seq<Stamped>): nat
  decreases |entries|
{
  if |entries| == 0 then 0
  else
    var passed := fenceStep(state, own, entries[0].isRun, entries[0].writer);
    (if passed.lost then 1 else 0) + lostCount(passed.state, own, entries[1..])
}

// The caller hears `lost` at most once over any read, and never once superseded.
lemma LostAtMostOnce(state: Fence, own: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  ensures state.superseded ==> lostCount(state, own, entries) == 0
  ensures lostCount(state, own, entries) <= 1
{
  if |entries| > 0 {
    var passed := fenceStep(state, own, entries[0].isRun, entries[0].writer);
    fenceStep_ensures(state, own, entries[0].isRun, entries[0].writer);
    LostAtMostOnce(passed.state, own, entries[1..]);
  }
}

// A journal with no run reads the fence like any other reader: it is never
// fenced, never superseded, and never hears `lost`, whatever the read holds.
lemma NoRunReadsLikeAnyReader(state: Fence, entries: seq<Stamped>)
  decreases |entries|
  requires !state.fenced && !state.superseded
  ensures !fenceFold(state, None, entries).fenced
  ensures !fenceFold(state, None, entries).superseded
  ensures lostCount(state, None, entries) == 0
{
  if |entries| > 0 {
    var passed := fenceStep(state, None, entries[0].isRun, entries[0].writer);
    fenceStep_ensures(state, None, entries[0].isRun, entries[0].writer);
    NoRunReadsLikeAnyReader(passed.state, entries[1..]);
  }
}

// After the fence of run r, a kept stamped entry that is not a run entry is r's.
lemma KeptAfterFenceIsTheFencesRun(state: Fence, own: Option<string>, writer: string, r: string)
  requires state.fence == Some(r)
  ensures fenceStep(state, own, false, Some(writer)).keep ==> writer == r
{
  fenceStep_ensures(state, own, false, Some(writer));
}

// Own fence, then another run's fence: superseded, and lost at exactly that step.
lemma OwnThenOtherSupersedes(state: Fence, own: string, other: string)
  requires own != other
  requires !state.superseded
  ensures fenceStep(fenceStep(state, Some(own), true, Some(own)).state, Some(own), true, Some(other)).state.superseded
  ensures fenceStep(fenceStep(state, Some(own), true, Some(own)).state, Some(own), true, Some(other)).lost
{
  var afterOwn := fenceStep(state, Some(own), true, Some(own)).state;
  fenceStep_ensures(state, Some(own), true, Some(own));
  sameWriter_ensures(Some(own), Some(own));
  sameWriter_ensures(Some(own), Some(other));
  fenceStep_ensures(afterOwn, Some(own), true, Some(other));
}

// Which entries a step keeps, and where the fence moves, never depend on
// who reads: two readers at the same fence keep the same entry.
lemma KeepIgnoresReader(state: Fence, a: Option<string>, b: Option<string>, isRun: bool, writer: Option<string>)
  ensures fenceStep(state, a, isRun, writer).keep == fenceStep(state, b, isRun, writer).keep
  ensures fenceStep(state, a, isRun, writer).state.fence == fenceStep(state, b, isRun, writer).state.fence
{
  fenceStep_ensures(state, a, isRun, writer);
  fenceStep_ensures(state, b, isRun, writer);
}

// Over a whole read, the fence two readers arrive at is the same when they
// started at the same fence, so the entries they keep are the same.
lemma FenceIgnoresReader(s: Fence, t: Fence, a: Option<string>, b: Option<string>, entries: seq<Stamped>)
  decreases |entries|
  requires s.fence == t.fence
  ensures fenceFold(s, a, entries).fence == fenceFold(t, b, entries).fence
{
  if |entries| > 0 {
    var ns := fenceStep(s, a, entries[0].isRun, entries[0].writer).state;
    var nt := fenceStep(t, b, entries[0].isRun, entries[0].writer).state;
    fenceStep_ensures(s, a, entries[0].isRun, entries[0].writer);
    fenceStep_ensures(t, b, entries[0].isRun, entries[0].writer);
    FenceIgnoresReader(ns, nt, a, b, entries[1..]);
  }
}

// A writable journal appends an entry every reader at the same fence keeps:
// the pure half of "every entry this journal appends, every reader keeps".
lemma WritableIsKeptByEveryReader(closed: bool, state: Fence, own: Option<string>, isRun: bool, reader: Option<string>)
  ensures writable(closed, state, own, isRun) ==> fenceStep(state, reader, isRun, own).keep
{
  writable_ensures(closed, state, own, isRun);
  KeepIgnoresReader(state, own, reader, isRun, own);
}

// The last seq the journal gives out: below the largest safe integer, so
// the successor of every cached seq is exact in a double.
const LAST_SEQ: int := 9007199254740990

// The seq counter over a cache, folded the way `remember` runs `advanceSeq`.
// Every cached seq is at most LAST_SEQ, because `positionOf` takes no other.
function counterFrom(start: int, seqs: seq<int>): int
  requires 0 <= start <= LAST_SEQ
  requires forall k :: 0 <= k < |seqs| ==> 0 <= seqs[k] <= LAST_SEQ
  decreases |seqs|
{
  if |seqs| == 0 then start else counterFrom(advanceSeq(start, seqs[0]), seqs[1..])
}

// The counter is at least every cached seq, so the next seq is one no cached
// entry holds. The journal refuses a write once the counter reaches LAST_SEQ.
lemma CounterCoversCache(start: int, seqs: seq<int>)
  requires 0 <= start <= LAST_SEQ
  requires forall k :: 0 <= k < |seqs| ==> 0 <= seqs[k] <= LAST_SEQ
  decreases |seqs|
  ensures counterFrom(start, seqs) >= start
  ensures 0 <= counterFrom(start, seqs) <= LAST_SEQ
  ensures forall k :: 0 <= k < |seqs| ==> counterFrom(start, seqs) >= seqs[k]
  ensures counterFrom(start, seqs) < LAST_SEQ ==>
    forall k :: 0 <= k < |seqs| ==> nextSeq(counterFrom(start, seqs)) > seqs[k]
{
  if |seqs| > 0 {
    advanceSeq_ensures(start, seqs[0]);
    CounterCoversCache(advanceSeq(start, seqs[0]), seqs[1..]);
  }
  if counterFrom(start, seqs) < LAST_SEQ {
    nextSeq_ensures(counterFrom(start, seqs));
  }
}

// The cursor over one read, folded the way `read` runs `scanned`.
function cursorFold(cursor: int, positions: seq<int>): int
  requires cursor >= 0
  requires forall k :: 0 <= k < |positions| ==> positions[k] >= 0
  decreases |positions|
{
  if |positions| == 0 then cursor else cursorFold(scanned(cursor, positions[0]), positions[1..])
}

// The cursor after a read is at least where it stood and at least every position scanned.
lemma CursorNeverMovesBack(cursor: int, positions: seq<int>)
  requires cursor >= 0
  requires forall k :: 0 <= k < |positions| ==> positions[k] >= 0
  decreases |positions|
  ensures cursorFold(cursor, positions) >= cursor
  ensures forall k :: 0 <= k < |positions| ==> cursorFold(cursor, positions) >= positions[k]
{
  if |positions| > 0 {
    scanned_ensures(cursor, positions[0]);
    CursorNeverMovesBack(scanned(cursor, positions[0]), positions[1..]);
  }
}
