// Generated by lsc from rules.verified.ts

function nextSeq(lastSeq: int): int
  requires (lastSeq >= 0)
{
  (lastSeq + 1)
}

lemma nextSeq_ensures(lastSeq: int)
  requires (lastSeq >= 0)
  ensures (nextSeq(lastSeq) == (lastSeq + 1))
  ensures (nextSeq(lastSeq) > lastSeq)
{
}

function refused(lastSeq: int, readThrough: int): bool
  requires (lastSeq >= 0)
  requires (readThrough >= 0)
{
  (lastSeq > readThrough)
}

lemma refused_ensures(lastSeq: int, readThrough: int)
  requires (lastSeq >= 0)
  requires (readThrough >= 0)
  ensures (refused(lastSeq, readThrough) <==> (lastSeq > readThrough))
  ensures (!(refused(lastSeq, readThrough)) ==> (readThrough >= lastSeq))
{
}

function voided(fenced: bool, stamped: bool, sameRun: bool): bool
{
  ((fenced && stamped) && !(sameRun))
}

lemma voided_ensures(fenced: bool, stamped: bool, sameRun: bool)
  ensures (voided(fenced, stamped, sameRun) ==> fenced)
  ensures (voided(fenced, stamped, sameRun) ==> stamped)
  ensures (voided(fenced, stamped, sameRun) ==> !(sameRun))
  ensures (sameRun ==> !(voided(fenced, stamped, sameRun)))
  ensures (fenced ==> stamped ==> !(sameRun) ==> voided(fenced, stamped, sameRun))
{
}

function supersedes(ownEntryLanded: bool, sameRun: bool): bool
{
  (ownEntryLanded && !(sameRun))
}

lemma supersedes_ensures(ownEntryLanded: bool, sameRun: bool)
  ensures (supersedes(ownEntryLanded, sameRun) <==> (ownEntryLanded && !(sameRun)))
  ensures (sameRun ==> !(supersedes(ownEntryLanded, sameRun)))
  ensures (!(ownEntryLanded) ==> !(supersedes(ownEntryLanded, sameRun)))
{
}
