// Generated by lsc from rules.verified.ts

datatype Option<T> = None | Some(value: T)

function MathMax(a: int, b: int): int { if a >= b then a else b }

datatype StoredEntry = StoredEntry(position: int)

datatype Fence = Fence(fence: Option<string>, fenced: bool, superseded: bool)

datatype Passed = Passed(state: Fence, keep: bool, lost: bool)

datatype Seen = Seen(kind: string, run: Option<string>)

datatype Keyed = fresh_ | replay | conflict

function sameWriter(own: Option<string>, writer: Option<string>): bool
{
  (((match own { case Some(i_) => true case None => false }) && (match writer { case Some(i_) => true case None => false })) && (own == writer))
}

lemma sameWriter_ensures(own: Option<string>, writer: Option<string>)
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(sameWriter(own, writer)))
  ensures ((match writer { case Some(i_) => false case None => true }) ==> !(sameWriter(own, writer)))
  ensures (match own { case Some(i_own_val) => (match writer { case Some(i_writer_val) => (sameWriter(own, writer) <==> (i_own_val == i_writer_val)) case None => true }) case None => true })
{
}

function nextSeq(lastSeq: int): int
  requires (lastSeq >= 0)
  requires (lastSeq < 9007199254740990)
{
  (lastSeq + 1)
}

lemma nextSeq_ensures(lastSeq: int)
  requires (lastSeq >= 0)
  requires (lastSeq < 9007199254740990)
  ensures (nextSeq(lastSeq) == (lastSeq + 1))
  ensures (nextSeq(lastSeq) > lastSeq)
  ensures (nextSeq(lastSeq) <= 9007199254740990)
{
}

function advanceSeq(lastSeq: int, seq_: int): int
  requires (lastSeq >= 0)
  requires (seq_ >= 0)
  requires (lastSeq <= 9007199254740990)
  requires (seq_ <= 9007199254740990)
{
  MathMax(lastSeq, seq_)
}

lemma advanceSeq_ensures(lastSeq: int, seq_: int)
  requires (lastSeq >= 0)
  requires (seq_ >= 0)
  requires (lastSeq <= 9007199254740990)
  requires (seq_ <= 9007199254740990)
  ensures (advanceSeq(lastSeq, seq_) >= lastSeq)
  ensures (advanceSeq(lastSeq, seq_) >= seq_)
  ensures ((advanceSeq(lastSeq, seq_) == lastSeq) || (advanceSeq(lastSeq, seq_) == seq_))
  ensures (advanceSeq(lastSeq, seq_) <= 9007199254740990)
  ensures ((advanceSeq(lastSeq, seq_) < 9007199254740990) ==> (nextSeq(advanceSeq(lastSeq, seq_)) > seq_))
  ensures ((advanceSeq(lastSeq, seq_) < 9007199254740990) ==> (nextSeq(advanceSeq(lastSeq, seq_)) > lastSeq))
{
}

function scanned(cursor: int, position: int): int
  requires (cursor >= 0)
  requires (position >= 0)
{
  MathMax(cursor, position)
}

lemma scanned_ensures(cursor: int, position: int)
  requires (cursor >= 0)
  requires (position >= 0)
  ensures (scanned(cursor, position) >= cursor)
  ensures (scanned(cursor, position) >= position)
  ensures ((scanned(cursor, position) == cursor) || (scanned(cursor, position) == position))
{
}

function nextPosition(head: int): int
{
  (head + 1)
}

lemma nextPosition_ensures(head: int)
  ensures (nextPosition(head) == (head + 1))
  ensures (nextPosition(head) > head)
{
}

function admit(head: int, expected: int): Option<int>
  requires (head >= 0)
{
  if (head == expected) then
    Option.Some(nextPosition(head))
  else
    Option.None
}

lemma admit_ensures(head: int, expected: int)
  requires (head >= 0)
  ensures ((match admit(head, expected) { case Some(i_) => true case None => false }) <==> (head == expected))
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val == nextPosition(head)) case None => true })
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val == (expected + 1)) case None => true })
  ensures (match admit(head, expected) { case Some(i_result_val) => (i_result_val > expected) case None => true })
  ensures ((head != expected) ==> (match admit(head, expected) { case Some(i_) => false case None => true }))
{
}

function readPosition(after: int, scanned: Option<int>): int
{
  match scanned {
    case Some(i_scanned_val) =>
      MathMax(after, i_scanned_val)
    case None =>
      after
  }
}

lemma readPosition_ensures(after: int, scanned: Option<int>)
  ensures (readPosition(after, scanned) >= after)
  ensures (match scanned { case Some(i_scanned_val) => (readPosition(after, scanned) >= i_scanned_val) case None => true })
  ensures ((match scanned { case Some(i_) => false case None => true }) ==> (readPosition(after, scanned) == after))
  ensures (match scanned { case Some(i_scanned_val) => ((i_scanned_val >= after) ==> (readPosition(after, scanned) == i_scanned_val)) case None => true })
  ensures (match scanned { case Some(i_scanned_val) => ((i_scanned_val < after) ==> (readPosition(after, scanned) == after)) case None => true })
{
}

function passFence(state: Fence, own: Option<string>, writer: Option<string>): Passed
{
  if sameWriter(own, writer) then
    Passed(Fence(writer, true, state.superseded), true, false)
  else
    var superseded := (state.superseded || state.fenced);
    Passed(Fence(writer, state.fenced, superseded), true, (superseded && !(state.superseded)))
}

lemma passFence_ensures(state: Fence, own: Option<string>, writer: Option<string>)
  ensures (passFence(state, own, writer).state.fence == writer)
  ensures passFence(state, own, writer).keep
  ensures (sameWriter(own, writer) ==> passFence(state, own, writer).state.fenced)
  ensures (sameWriter(own, writer) ==> (passFence(state, own, writer).state.superseded == state.superseded))
  ensures (!(sameWriter(own, writer)) ==> (passFence(state, own, writer).state.fenced == state.fenced))
  ensures (!(sameWriter(own, writer)) ==> state.fenced ==> passFence(state, own, writer).state.superseded)
  ensures (state.superseded ==> passFence(state, own, writer).state.superseded)
  ensures (state.fenced ==> passFence(state, own, writer).state.fenced)
  ensures (!(state.superseded) ==> !(state.fenced) ==> !(passFence(state, own, writer).state.superseded))
  ensures (passFence(state, own, writer).lost <==> (!(state.superseded) && passFence(state, own, writer).state.superseded))
{
}

function passEntry(state: Fence, writer: Option<string>): Passed
{
  var keep := (((match state.fence { case Some(i_) => false case None => true }) || (match writer { case Some(i_) => false case None => true })) || (writer == state.fence));
  Passed(state, keep, false)
}

lemma passEntry_ensures(state: Fence, writer: Option<string>)
  ensures (passEntry(state, writer).state == state)
  ensures !(passEntry(state, writer).lost)
  ensures ((match state.fence { case Some(i_) => false case None => true }) ==> passEntry(state, writer).keep)
  ensures ((match writer { case Some(i_) => false case None => true }) ==> passEntry(state, writer).keep)
  ensures (match state.fence { case Some(i_state_fence_val) => (match writer { case Some(i_writer_val) => (passEntry(state, writer).keep <==> (i_state_fence_val == i_writer_val)) case None => true }) case None => true })
{
}

function fenceStep(state: Fence, own: Option<string>, isRun: bool, writer: Option<string>): Passed
{
  if isRun then
    passFence(state, own, writer)
  else
    passEntry(state, writer)
}

lemma fenceStep_ensures(state: Fence, own: Option<string>, isRun: bool, writer: Option<string>)
  ensures (state.superseded ==> fenceStep(state, own, isRun, writer).state.superseded)
  ensures (state.fenced ==> fenceStep(state, own, isRun, writer).state.fenced)
  ensures (isRun ==> fenceStep(state, own, isRun, writer).keep)
  ensures (isRun ==> (fenceStep(state, own, isRun, writer).state.fence == writer))
  ensures (!(isRun) ==> (fenceStep(state, own, isRun, writer).state == state))
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (!(isRun) ==> (i_writer_val != i_state_fence_val) ==> !(fenceStep(state, own, isRun, writer).keep)) case None => true }) case None => true })
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (!(isRun) ==> (i_writer_val == i_state_fence_val) ==> fenceStep(state, own, isRun, writer).keep) case None => true }) case None => true })
  ensures (!(isRun) ==> (match state.fence { case Some(i_) => false case None => true }) ==> fenceStep(state, own, isRun, writer).keep)
  ensures (!(isRun) ==> (match writer { case Some(i_) => false case None => true }) ==> fenceStep(state, own, isRun, writer).keep)
  ensures (match writer { case Some(i_writer_val) => (match state.fence { case Some(i_state_fence_val) => (fenceStep(state, own, isRun, writer).keep ==> !(isRun) ==> (i_writer_val == i_state_fence_val)) case None => true }) case None => true })
  ensures (fenceStep(state, own, isRun, writer).lost ==> isRun)
  ensures (fenceStep(state, own, isRun, writer).lost ==> (!(state.superseded) && fenceStep(state, own, isRun, writer).state.superseded))
  ensures (isRun ==> sameWriter(own, writer) ==> fenceStep(state, own, isRun, writer).state.fenced)
  ensures (isRun ==> sameWriter(own, writer) ==> (fenceStep(state, own, isRun, writer).state.superseded == state.superseded))
  ensures (isRun ==> !(sameWriter(own, writer)) ==> state.fenced ==> fenceStep(state, own, isRun, writer).state.superseded)
  ensures (isRun ==> !(sameWriter(own, writer)) ==> state.fenced ==> !(state.superseded) ==> fenceStep(state, own, isRun, writer).lost)
  ensures (!(state.fenced) ==> !((isRun && sameWriter(own, writer))) ==> (fenceStep(state, own, isRun, writer).state.fenced == false))
  ensures (!(state.fenced) ==> !(state.superseded) ==> !(fenceStep(state, own, isRun, writer).state.superseded))
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(state.fenced) ==> !(fenceStep(state, own, isRun, writer).state.fenced))
  ensures ((match own { case Some(i_) => false case None => true }) ==> !(state.fenced) ==> !(state.superseded) ==> (!(fenceStep(state, own, isRun, writer).state.superseded) && !(fenceStep(state, own, isRun, writer).lost)))
{
}

function keyed(seen: Option<Seen>, kind: string, fenceKind: string, own: Option<string>): Keyed
{
  match seen {
    case Some(i_seen_val) =>
      if (i_seen_val.kind != kind) then
        Keyed.conflict
      else
        if ((kind == fenceKind) && !(sameWriter(own, i_seen_val.run))) then
          Keyed.conflict
        else
          Keyed.replay
    case None =>
      Keyed.fresh_
  }
}

lemma keyed_ensures(seen: Option<Seen>, kind: string, fenceKind: string, own: Option<string>)
  ensures ((match seen { case Some(i_) => false case None => true }) ==> keyed(seen, kind, fenceKind, own).fresh_?)
  ensures (match seen { case Some(i_seen_val) => (!keyed(seen, kind, fenceKind, own).fresh_?) case None => true })
  ensures (keyed(seen, kind, fenceKind, own).fresh_? ==> (match seen { case Some(i_) => false case None => true }))
  ensures ((match seen { case Some(i_) => false case None => true }) ==> (!keyed(seen, kind, fenceKind, own).replay?))
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind != kind) ==> (!keyed(seen, kind, fenceKind, own).replay?)) case None => true })
  ensures ((match seen { case Some(i_) => false case None => true }) ==> (!keyed(seen, kind, fenceKind, own).conflict?))
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind != kind) ==> keyed(seen, kind, fenceKind, own).conflict?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> (kind != fenceKind) ==> keyed(seen, kind, fenceKind, own).replay?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> sameWriter(own, i_seen_val.run) ==> keyed(seen, kind, fenceKind, own).replay?) case None => true })
  ensures (match seen { case Some(i_seen_val) => ((i_seen_val.kind == kind) ==> (kind == fenceKind) ==> !(sameWriter(own, i_seen_val.run)) ==> keyed(seen, kind, fenceKind, own).conflict?) case None => true })
{
}

function writable(closed: bool, state: Fence, own: Option<string>, isRun: bool): bool
{
  ((!(closed) && !(state.superseded)) && fenceStep(state, own, isRun, own).keep)
}

lemma writable_ensures(closed: bool, state: Fence, own: Option<string>, isRun: bool)
  ensures (closed ==> !(writable(closed, state, own, isRun)))
  ensures (state.superseded ==> !(writable(closed, state, own, isRun)))
  ensures (writable(closed, state, own, isRun) ==> fenceStep(state, own, isRun, own).keep)
  ensures (!(closed) ==> !(state.superseded) ==> fenceStep(state, own, isRun, own).keep ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> isRun ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> (match own { case Some(i_) => false case None => true }) ==> writable(closed, state, own, isRun))
  ensures (!(closed) ==> !(state.superseded) ==> (match state.fence { case Some(i_) => false case None => true }) ==> writable(closed, state, own, isRun))
  ensures (match state.fence { case Some(i_state_fence_val) => (match own { case Some(i_own_val) => (!(closed) ==> !(state.superseded) ==> (i_own_val == i_state_fence_val) ==> writable(closed, state, own, isRun)) case None => true }) case None => true })
  ensures (match own { case Some(i_own_val) => (match state.fence { case Some(i_state_fence_val) => ((i_own_val != i_state_fence_val) ==> !(isRun) ==> !(writable(closed, state, own, isRun))) case None => true }) case None => true })
{
}

method visibleEntries(entries: seq<StoredEntry>, after: int) returns (res: seq<StoredEntry>)
  ensures (|res| <= |entries|)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i].position > after))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in entries))
  ensures forall i: int :: ((0 <= i) ==> (i < |entries|) ==> (entries[i].position > after) ==> (entries[i] in res))
  ensures forall i: int :: ((0 <= i) ==> (i < |entries|) ==> (entries[i].position <= after) ==> !((entries[i] in res)))
{
  var out: seq<StoredEntry> := [];
  var i := 0;
  while (i < |entries|)
    invariant (0 <= i)
    invariant (i <= |entries|)
    invariant (|out| <= i)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k].position > after))
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] in entries))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> (entries[k].position > after) ==> (entries[k] in out))
    decreases (|entries| - i)
  {
    var stored := (if ((0 <= i) && (i < |entries|)) then entries[i] else StoredEntry(after));
    if (stored.position > after) {
      out := (out + [stored]);
    }
    i := (i + 1);
  }
  return out;
}
