// Generated by lsc from distributed.verified.ts

function nextSequence(lastSequence: int): int
  requires (lastSequence >= 0)
{
  (lastSequence + 1)
}

lemma nextSequence_ensures(lastSequence: int)
  requires (lastSequence >= 0)
  ensures (nextSequence(lastSequence) == (lastSequence + 1))
  ensures (nextSequence(lastSequence) > lastSequence)
{
}

function privateAllocationsCollide(snapshot: int): bool
  requires (snapshot >= 0)
{
  var first := nextSequence(snapshot);
  var second := nextSequence(snapshot);
  (first == second)
}

lemma privateAllocationsCollide_ensures(snapshot: int)
  requires (snapshot >= 0)
  ensures privateAllocationsCollide(snapshot)
{
}

function acceptsGeneration(current: int, presented: int): bool
  requires (current >= 1)
  requires (presented >= 1)
{
  (current == presented)
}

lemma acceptsGeneration_ensures(current: int, presented: int)
  requires (current >= 1)
  requires (presented >= 1)
  ensures (acceptsGeneration(current, presented) <==> (current == presented))
{
}

function foldLeaseEnded(knownEnded: bool, rowEnded: bool): bool
{
  (knownEnded || rowEnded)
}

lemma foldLeaseEnded_ensures(knownEnded: bool, rowEnded: bool)
  ensures (knownEnded ==> foldLeaseEnded(knownEnded, rowEnded))
  ensures (foldLeaseEnded(knownEnded, rowEnded) <==> (knownEnded || rowEnded))
{
}

function acceptsAppend(currentGeneration: int, presentedGeneration: int, lastSequence: int, readThrough: int, keySeen: bool): bool
  requires (currentGeneration >= 1)
  requires (presentedGeneration >= 1)
  requires (lastSequence >= 0)
  requires (readThrough >= 0)
{
  (((currentGeneration == presentedGeneration) && (lastSequence == readThrough)) && !(keySeen))
}

lemma acceptsAppend_ensures(currentGeneration: int, presentedGeneration: int, lastSequence: int, readThrough: int, keySeen: bool)
  requires (currentGeneration >= 1)
  requires (presentedGeneration >= 1)
  requires (lastSequence >= 0)
  requires (readThrough >= 0)
  ensures (acceptsAppend(currentGeneration, presentedGeneration, lastSequence, readThrough, keySeen) ==> (currentGeneration == presentedGeneration))
  ensures (acceptsAppend(currentGeneration, presentedGeneration, lastSequence, readThrough, keySeen) ==> (lastSequence == readThrough))
  ensures (acceptsAppend(currentGeneration, presentedGeneration, lastSequence, readThrough, keySeen) ==> !(keySeen))
  ensures ((currentGeneration == presentedGeneration) ==> (lastSequence == readThrough) ==> !(keySeen) ==> acceptsAppend(currentGeneration, presentedGeneration, lastSequence, readThrough, keySeen))
{
}
