// Generated by lsc from rules.verified.ts

function rangeWellFormed(from: int, through: int): bool
{
  ((from >= 1) && (from <= through))
}

lemma rangeWellFormed_ensures(from: int, through: int)
  ensures (rangeWellFormed(from, through) <==> ((1 <= from) && (from <= through)))
  ensures (rangeWellFormed(from, through) ==> (through >= 1))
{
}

function positiveBounded(value: int): bool
{
  ((value >= 1) && (value <= 9007199254740991))
}

lemma positiveBounded_ensures(value: int)
  ensures (positiveBounded(value) <==> ((1 <= value) && (value <= 9007199254740991)))
{
}
