// Generated by lsc from rules.verified.ts

datatype Option<T> = None | Some(value: T)

function SeqFind<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFind(s, p).Some? ==> p(SeqFind(s, p).value)
  ensures SeqFind(s, p).Some? ==> SeqFind(s, p).value in s
  ensures SeqFind(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFind(s, p).value && p(s[i]) &&
                     (forall j: nat :: j < i ==> !p(s[j]))
  ensures SeqFind(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[0]) then Some(s[0])
  else SeqFind(s[1..], p)
}

function MathMin(a: int, b: int): int { if a <= b then a else b }

function MathMax(a: int, b: int): int { if a >= b then a else b }

datatype LeasePhase = running | ended

datatype LeaseEndReason = released | failed | revoked | expired | abandoned

datatype Purpose = respond | summarize

datatype Intent = said | seated | unseated

datatype Freshness = invalid | missed | fresh_

datatype OpenExchange = OpenExchange(owner: string, from: int)

datatype CloseRef = CloseRef(owner: string, from: int, through: int)

datatype Hold = running(id: string, at: string, claimedAt: string, since: int, readThrough: int, expiresAt: int) | ended(id: string, at: string, claimedAt: string, since: int, readThrough: int, reason: LeaseEndReason, cancelled: Option<bool>, until: int)

datatype Change = running(id: string, expiresAt: int, at: string, readThrough: int) | ended(id: string, reason: LeaseEndReason, at: string, readThrough: int)

datatype Taken = running(readThrough: int, position: int) | ended(reason: LeaseEndReason, readThrough: int, position: int)

datatype Schedule = Schedule(attempt: int, notBefore: Option<int>)

datatype Ending = revoked | expired | stays

datatype Source = message | closed

datatype LiveLease = LiveLease(source: Source, seat: string, phase: LeasePhase, expiresAt: int)

datatype OwedActivation = OwedActivation(source: Source, seat: string)

datatype ActivationFields = ActivationFields(source: Source, position: int, seat: string, attempt: int)

datatype CloseFact = CloseFact(owner: string, from: int, through: int, summary: Option<string>)

datatype GrantPurpose = respond(message: int) | summarize(exchange: int, person: string, through: int)

datatype Grant = Grant(seat: string, attempt: int, purpose: GrantPurpose)

datatype Draft = running | ended(reason: LeaseEndReason, cancelled: bool)

datatype Verdict = published | pending(owed: bool) | silent | failed

datatype Range = Range(from: int, through: int)

datatype Found = closed(from: int) | open(from: int) | outside

datatype LeaseKind = claim | renew

datatype Admission = ended | granted | held

datatype Stamped = Stamped(to: string, covers: Range)

datatype PresenceKind = arrived | left

datatype Outcome = refused | unchanged_ | written

datatype MembershipKind = seated | unseated

datatype Authority = granted | refused | stale

function expired(expiry: int, now: int): bool
{
  (expiry <= now)
}

lemma expired_ensures(expiry: int, now: int)
  ensures (expired(expiry, now) <==> (expiry <= now))
{
}

function coversAttempt(ended: bool, until: int, seq_: int): bool
{
  (!(ended) || (seq_ <= until))
}

lemma coversAttempt_ensures(ended: bool, until: int, seq_: int)
  ensures (!(ended) ==> coversAttempt(ended, until, seq_))
  ensures (ended ==> (coversAttempt(ended, until, seq_) <==> (seq_ <= until)))
  ensures (coversAttempt(ended, until, seq_) ==> forall earlier: int :: ((earlier <= seq_) ==> coversAttempt(ended, until, earlier)))
{
}

function givesUp(attempts: int, cap: int): bool
  requires (attempts >= 0)
  requires (cap >= 1)
{
  (attempts >= cap)
}

lemma givesUp_ensures(attempts: int, cap: int)
  requires (attempts >= 0)
  requires (cap >= 1)
  ensures (givesUp(attempts, cap) <==> (attempts >= cap))
  ensures (!(givesUp(attempts, cap)) ==> ((attempts + 1) <= cap))
{
}

function nextAttempt(attempts: int): int
  requires (attempts >= 0)
{
  (attempts + 1)
}

lemma nextAttempt_ensures(attempts: int)
  requires (attempts >= 0)
  ensures (nextAttempt(attempts) == (attempts + 1))
  ensures (nextAttempt(attempts) >= 1)
{
}

function beforeCancellation(position: int, cancelledAt: int): bool
{
  (position < cancelledAt)
}

lemma beforeCancellation_ensures(position: int, cancelledAt: int)
  ensures (beforeCancellation(position, cancelledAt) <==> (position < cancelledAt))
{
}

function mayEnd(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool): bool
{
  match known {
    case Some(i_known_val) =>
      if (i_known_val.ended? || reason.abandoned?) then
        false
      else
        (reason.revoked? || (pastExpiry == reason.expired?))
    case None =>
      (reason.revoked? || reason.abandoned?)
  }
}

lemma mayEnd_ensures(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool)
  ensures ((match known { case Some(i_) => false case None => true }) ==> (mayEnd(known, reason, pastExpiry) <==> (reason.revoked? || reason.abandoned?)))
  ensures (match known { case Some(i_known_val) => (i_known_val.ended? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.abandoned? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.revoked? ==> mayEnd(known, reason, pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.expired? ==> (mayEnd(known, reason, pastExpiry) <==> pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.released? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.failed? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
{
}

function permits(purpose: Purpose, intent: Intent): bool
{
  match intent {
    case said =>
      (purpose.respond? || purpose.summarize?)
    case seated =>
      purpose.respond?
    case unseated =>
      purpose.respond?
  }
}

lemma permits_ensures(purpose: Purpose, intent: Intent)
  ensures (intent.said? ==> permits(purpose, intent))
  ensures ((!intent.said?) ==> (permits(purpose, intent) <==> purpose.respond?))
  ensures (purpose.summarize? ==> (permits(purpose, intent) <==> intent.said?))
  ensures (purpose.respond? ==> permits(purpose, intent))
{
}

function leaseExpiry(now: int, claimedAt: int, expiry: int, deadline: int): int
  requires (expiry >= 1)
  requires (deadline >= 1)
{
  MathMin((now + expiry), (claimedAt + deadline))
}

lemma leaseExpiry_ensures(now: int, claimedAt: int, expiry: int, deadline: int)
  requires (expiry >= 1)
  requires (deadline >= 1)
  ensures (leaseExpiry(now, claimedAt, expiry, deadline) <= (now + expiry))
  ensures (leaseExpiry(now, claimedAt, expiry, deadline) <= (claimedAt + deadline))
  ensures ((leaseExpiry(now, claimedAt, expiry, deadline) == (now + expiry)) || (leaseExpiry(now, claimedAt, expiry, deadline) == (claimedAt + deadline)))
  ensures ((leaseExpiry(now, claimedAt, expiry, deadline) > now) <==> ((claimedAt + deadline) > now))
  ensures ((claimedAt == now) ==> (leaseExpiry(now, claimedAt, expiry, deadline) > now))
  ensures (!(expired(leaseExpiry(now, claimedAt, expiry, deadline), now)) <==> !(expired((claimedAt + deadline), now)))
{
}

function acknowledged(prior: Option<int>, incoming: int): int
  requires (incoming >= 0)
  requires (match prior { case Some(i_prior_val) => (i_prior_val >= 0) case None => true })
{
  match prior {
    case Some(i_prior_val) =>
      MathMax(i_prior_val, incoming)
    case None =>
      incoming
  }
}

lemma acknowledged_ensures(prior: Option<int>, incoming: int)
  requires (incoming >= 0)
  requires (match prior { case Some(i_prior_val) => (i_prior_val >= 0) case None => true })
  ensures (match prior { case Some(i_prior_val) => (acknowledged(prior, incoming) >= i_prior_val) case None => true })
  ensures (acknowledged(prior, incoming) >= incoming)
  ensures ((match prior { case Some(i_) => false case None => true }) ==> (acknowledged(prior, incoming) == incoming))
  ensures (match prior { case Some(i_prior_val) => ((acknowledged(prior, incoming) == i_prior_val) || (acknowledged(prior, incoming) == incoming)) case None => true })
  ensures (match prior { case Some(i_prior_val) => ((incoming == 0) ==> (acknowledged(prior, incoming) == i_prior_val)) case None => true })
  ensures (acknowledged(prior, incoming) >= 0)
{
}

function onRecord(position: int, lastSeq: int): bool
  requires (lastSeq >= 0)
{
  ((position >= 0) && (position <= lastSeq))
}

lemma onRecord_ensures(position: int, lastSeq: int)
  requires (lastSeq >= 0)
  ensures (onRecord(position, lastSeq) <==> ((0 <= position) && (position <= lastSeq)))
{
}

function speechFreshness(readThrough: Option<int>, lastSeq: int): Freshness
  requires (lastSeq >= 0)
{
  match readThrough {
    case Some(i_readThrough_val) =>
      if !(onRecord(i_readThrough_val, lastSeq)) then
        Freshness.invalid
      else
        if (i_readThrough_val < lastSeq) then
          Freshness.missed
        else
          Freshness.fresh_
    case None =>
      Freshness.invalid
  }
}

lemma speechFreshness_ensures(readThrough: Option<int>, lastSeq: int)
  requires (lastSeq >= 0)
  ensures ((match readThrough { case Some(i_) => false case None => true }) ==> speechFreshness(readThrough, lastSeq).invalid?)
  ensures (match readThrough { case Some(i_readThrough_val) => (speechFreshness(readThrough, lastSeq).invalid? <==> !(onRecord(i_readThrough_val, lastSeq))) case None => true })
  ensures (match readThrough { case Some(i_readThrough_val) => (speechFreshness(readThrough, lastSeq).fresh_? <==> (i_readThrough_val == lastSeq)) case None => true })
  ensures (match readThrough { case Some(i_readThrough_val) => (speechFreshness(readThrough, lastSeq).missed? <==> ((0 <= i_readThrough_val) && (i_readThrough_val < lastSeq))) case None => true })
  ensures (speechFreshness(readThrough, lastSeq).missed? ==> (lastSeq > 0))
{
}

function admitsClose(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool): bool
{
  match open {
    case Some(i_open_val) =>
      ((((i_open_val.from == close.from) && (i_open_val.owner == close.owner)) && (close.through == lastSeq)) && !(exchangeLive))
    case None =>
      false
  }
}

lemma admitsClose_ensures(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool)
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> (match open { case Some(i_) => true case None => false }))
  ensures (match open { case Some(i_open_val) => (admitsClose(open, close, lastSeq, exchangeLive) <==> ((((i_open_val.from == close.from) && (i_open_val.owner == close.owner)) && (close.through == lastSeq)) && !(exchangeLive))) case None => true })
  ensures (exchangeLive ==> !(admitsClose(open, close, lastSeq, exchangeLive)))
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> (close.through == lastSeq))
{
}

function coversClose(summaryFrom: int, summaryThrough: int, closeFrom: int, closeThrough: int): bool
{
  ((summaryFrom <= closeFrom) && (summaryThrough >= closeThrough))
}

lemma coversClose_ensures(summaryFrom: int, summaryThrough: int, closeFrom: int, closeThrough: int)
  ensures (coversClose(summaryFrom, summaryThrough, closeFrom, closeThrough) <==> ((summaryFrom <= closeFrom) && (summaryThrough >= closeThrough)))
{
}

function coversExchange(summaryTo: string, summaryFrom: int, summaryThrough: int, owner: string, from: int, through: int): bool
{
  ((summaryTo == owner) && coversClose(summaryFrom, summaryThrough, from, through))
}

lemma coversExchange_ensures(summaryTo: string, summaryFrom: int, summaryThrough: int, owner: string, from: int, through: int)
  ensures (coversExchange(summaryTo, summaryFrom, summaryThrough, owner, from, through) <==> (((summaryTo == owner) && (summaryFrom <= from)) && (summaryThrough >= through)))
  ensures (coversExchange(summaryTo, summaryFrom, summaryThrough, owner, from, through) ==> (summaryTo == owner))
  ensures (coversExchange(summaryTo, summaryFrom, summaryThrough, owner, from, through) ==> (from <= through) ==> (summaryFrom <= summaryThrough))
  ensures (coversExchange(summaryTo, summaryFrom, summaryThrough, owner, from, through) <==> ((summaryTo == owner) && coversClose(summaryFrom, summaryThrough, from, through)))
{
}

function survivesCancellation(position: int, cancelledAt: Option<int>): bool
{
  match cancelledAt {
    case Some(i_cancelledAt_val) =>
      !(beforeCancellation(position, i_cancelledAt_val))
    case None =>
      true
  }
}

lemma survivesCancellation_ensures(position: int, cancelledAt: Option<int>)
  ensures ((match cancelledAt { case Some(i_) => false case None => true }) ==> survivesCancellation(position, cancelledAt))
  ensures (match cancelledAt { case Some(i_cancelledAt_val) => (survivesCancellation(position, cancelledAt) <==> !(beforeCancellation(position, i_cancelledAt_val))) case None => true })
  ensures (match cancelledAt { case Some(i_cancelledAt_val) => (survivesCancellation(position, cancelledAt) <==> (position >= i_cancelledAt_val)) case None => true })
{
}

function applyChange(known: Option<Hold>, change: Change, seq_: int): Hold
  requires (seq_ >= 1)
  requires (change.readThrough >= 0)
  requires (match known { case Some(i_known_val) => ((i_known_val.readThrough >= 0) && (i_known_val.since <= seq_)) case None => true })
{
  match known {
    case Some(i_known_val) =>
      if i_known_val.ended? then
        i_known_val
      else
        var since := (match known { case Some(i_known_val) => i_known_val.since case None => seq_ });
        var claimedAt := (match known { case Some(i_known_val) => i_known_val.claimedAt case None => change.at });
        var prior := (match known { case Some(i_known_val) => i_known_val.readThrough case None => 0 });
        var readThrough := MathMax(prior, change.readThrough);
        match change {
          case running(i_change_id, i_change_expiresAt, i_change_at, i_change_readThrough) =>
            Hold.running(i_change_id, i_change_at, claimedAt, since, readThrough, i_change_expiresAt)
          case ended(i_change_id, i_change_reason, i_change_at, i_change_readThrough) =>
            Hold.ended(i_change_id, i_change_at, claimedAt, since, readThrough, i_change_reason, None, seq_)
        }
    case None =>
      var since := (match known { case Some(i_known_val) => i_known_val.since case None => seq_ });
      var claimedAt := (match known { case Some(i_known_val) => i_known_val.claimedAt case None => change.at });
      var prior := (match known { case Some(i_known_val) => i_known_val.readThrough case None => 0 });
      var readThrough := MathMax(prior, change.readThrough);
      match change {
        case running(i_change_id, i_change_expiresAt, i_change_at, i_change_readThrough) =>
          Hold.running(i_change_id, i_change_at, claimedAt, since, readThrough, i_change_expiresAt)
        case ended(i_change_id, i_change_reason, i_change_at, i_change_readThrough) =>
          Hold.ended(i_change_id, i_change_at, claimedAt, since, readThrough, i_change_reason, None, seq_)
      }
  }
}

lemma applyChange_ensures(known: Option<Hold>, change: Change, seq_: int)
  requires (seq_ >= 1)
  requires (change.readThrough >= 0)
  requires (match known { case Some(i_known_val) => ((i_known_val.readThrough >= 0) && (i_known_val.since <= seq_)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.ended? ==> (applyChange(known, change, seq_) == i_known_val)) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> ((applyChange(known, change, seq_).since == seq_) && (applyChange(known, change, seq_).claimedAt == change.at)))
  ensures (match known { case Some(i_known_val) => ((applyChange(known, change, seq_).since == i_known_val.since) && (applyChange(known, change, seq_).claimedAt == i_known_val.claimedAt)) case None => true })
  ensures (match known { case Some(i_known_val) => (applyChange(known, change, seq_).readThrough >= i_known_val.readThrough) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> (applyChange(known, change, seq_).readThrough == change.readThrough))
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> (applyChange(known, change, seq_).readThrough >= change.readThrough)) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> ((applyChange(known, change, seq_).id == change.id) && (applyChange(known, change, seq_).at == change.at)))
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> ((applyChange(known, change, seq_).id == change.id) && (applyChange(known, change, seq_).at == change.at))) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> change.ended? ==> ((applyChange(known, change, seq_).ended? && (applyChange(known, change, seq_).until == seq_)) && (applyChange(known, change, seq_).reason == change.reason)))
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> change.ended? ==> ((applyChange(known, change, seq_).ended? && (applyChange(known, change, seq_).until == seq_)) && (applyChange(known, change, seq_).reason == change.reason))) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> change.running? ==> (applyChange(known, change, seq_).running? && (applyChange(known, change, seq_).expiresAt == change.expiresAt)))
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> change.running? ==> (applyChange(known, change, seq_).running? && (applyChange(known, change, seq_).expiresAt == change.expiresAt))) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> applyChange(known, change, seq_).ended? ==> (applyChange(known, change, seq_).since <= applyChange(known, change, seq_).until))
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> applyChange(known, change, seq_).ended? ==> (applyChange(known, change, seq_).since <= applyChange(known, change, seq_).until)) case None => true })
{
}

function markedCancelled(hold: Hold): bool
{
  ((hold.ended? && hold.reason.revoked?) && (match hold.cancelled { case Some(i_value) => (i_value == true) case None => false }))
}

lemma markedCancelled_ensures(hold: Hold)
  ensures (markedCancelled(hold) ==> hold.ended?)
  ensures (markedCancelled(hold) ==> hold.reason.revoked?)
{
}

function cancelHold(hold: Hold, position: int, cancelledAt: int, at: string): Hold
  requires (hold.since <= cancelledAt)
{
  if (hold.ended? || !(beforeCancellation(position, cancelledAt))) then
    hold
  else
    Hold.ended(hold.id, at, hold.claimedAt, hold.since, hold.readThrough, LeaseEndReason.revoked, Some(true), cancelledAt)
}

lemma cancelHold_ensures(hold: Hold, position: int, cancelledAt: int, at: string)
  requires (hold.since <= cancelledAt)
  ensures (hold.ended? ==> (cancelHold(hold, position, cancelledAt, at) == hold))
  ensures (hold.running? ==> !(beforeCancellation(position, cancelledAt)) ==> (cancelHold(hold, position, cancelledAt, at) == hold))
  ensures (hold.running? ==> beforeCancellation(position, cancelledAt) ==> ((((cancelHold(hold, position, cancelledAt, at).ended? && cancelHold(hold, position, cancelledAt, at).reason.revoked?) && markedCancelled(cancelHold(hold, position, cancelledAt, at))) && (cancelHold(hold, position, cancelledAt, at).until == cancelledAt)) && (cancelHold(hold, position, cancelledAt, at).at == at)))
  ensures (cancelHold(hold, position, cancelledAt, at).readThrough == hold.readThrough)
  ensures (cancelHold(hold, position, cancelledAt, at).since == hold.since)
  ensures (cancelHold(hold, position, cancelledAt, at).claimedAt == hold.claimedAt)
  ensures (cancelHold(hold, position, cancelledAt, at).id == hold.id)
  ensures (cancelHold(hold, position, cancelledAt, at).ended? ==> hold.running? ==> (cancelHold(hold, position, cancelledAt, at).since <= cancelHold(hold, position, cancelledAt, at).until))
  ensures (markedCancelled(cancelHold(hold, position, cancelledAt, at)) ==> !(markedCancelled(hold)) ==> (hold.running? && beforeCancellation(position, cancelledAt)))
{
}

function isExpired(phase: LeasePhase, expiresAt: int, now: int): bool
{
  (phase.running? && expired(expiresAt, now))
}

lemma isExpired_ensures(phase: LeasePhase, expiresAt: int, now: int)
  ensures (isExpired(phase, expiresAt, now) <==> (phase.running? && expired(expiresAt, now)))
  ensures (isExpired(phase, expiresAt, now) ==> phase.running?)
{
}

function isLive(phase: LeasePhase, expiresAt: int, now: int): bool
{
  (phase.running? && !(isExpired(phase, expiresAt, now)))
}

lemma isLive_ensures(phase: LeasePhase, expiresAt: int, now: int)
  ensures (isLive(phase, expiresAt, now) <==> (phase.running? && (now < expiresAt)))
  ensures !((isLive(phase, expiresAt, now) && isExpired(phase, expiresAt, now)))
  ensures (phase.running? ==> (isLive(phase, expiresAt, now) || isExpired(phase, expiresAt, now)))
  ensures (phase.ended? ==> !(isLive(phase, expiresAt, now)))
{
}

function cameToNothing(reason: LeaseEndReason): bool
{
  (reason.failed? || reason.expired?)
}

lemma cameToNothing_ensures(reason: LeaseEndReason)
  ensures (cameToNothing(reason) <==> (reason.failed? || reason.expired?))
{
}

function answers(lease: Taken, seq_: int): bool
  requires (seq_ >= 1)
{
  match lease {
    case running(i_lease_readThrough, i_lease_position) =>
      true
    case ended(i_lease_reason, i_lease_readThrough, i_lease_position) =>
      if cameToNothing(i_lease_reason) then
        false
      else
        (((i_lease_reason.abandoned? || i_lease_reason.revoked?) && (i_lease_position == seq_)) || (i_lease_readThrough >= seq_))
  }
}

lemma answers_ensures(lease: Taken, seq_: int)
  requires (seq_ >= 1)
  ensures (lease.running? ==> answers(lease, seq_))
  ensures (lease.ended? ==> cameToNothing(lease.reason) ==> !(answers(lease, seq_)))
  ensures (lease.ended? ==> lease.reason.released? ==> (answers(lease, seq_) <==> (lease.readThrough >= seq_)))
  ensures (lease.ended? ==> (lease.reason.abandoned? || lease.reason.revoked?) ==> (answers(lease, seq_) <==> ((lease.position == seq_) || (lease.readThrough >= seq_))))
  ensures (lease.ended? ==> (lease.readThrough < seq_) ==> (lease.position != seq_) ==> !(answers(lease, seq_)))
{
}

function wakeAnswered(taken: seq<Taken>, seq_: int): bool
  requires (seq_ >= 1)
{
  (exists lease :: lease in taken && answers(lease, seq_))
}

lemma wakeAnswered_ensures(taken: seq<Taken>, seq_: int)
  requires (seq_ >= 1)
  ensures (wakeAnswered(taken, seq_) <==> exists i: int :: (((0 <= i) && (i < |taken|)) && answers(taken[i], seq_)))
  ensures (!(wakeAnswered(taken, seq_)) ==> forall i: int :: ((0 <= i) ==> (i < |taken|) ==> taken[i].ended?))
  ensures (!(wakeAnswered(taken, seq_)) ==> forall i: int :: ((0 <= i) ==> (i < |taken|) ==> (taken[i].ended? && (cameToNothing(taken[i].reason) || (taken[i].readThrough < seq_)))))
{
}

function countsAgainst(lease: Taken, seq_: int): bool
  requires (seq_ >= 1)
{
  match lease {
    case running(i_lease_readThrough, i_lease_position) =>
      false
    case ended(i_lease_reason, i_lease_readThrough, i_lease_position) =>
      (cameToNothing(i_lease_reason) || (i_lease_position == seq_))
  }
}

lemma countsAgainst_ensures(lease: Taken, seq_: int)
  requires (seq_ >= 1)
  ensures (lease.running? ==> !(countsAgainst(lease, seq_)))
  ensures (lease.ended? ==> cameToNothing(lease.reason) ==> countsAgainst(lease, seq_))
  ensures (lease.ended? ==> !(cameToNothing(lease.reason)) ==> (countsAgainst(lease, seq_) <==> (lease.position == seq_)))
{
}

function schedule(unsuccessful: int, last: int, backoff: int): Schedule
  requires (unsuccessful >= 0)
  requires (last >= 0)
{
  Schedule(nextAttempt(unsuccessful), (if (unsuccessful == 0) then Option.None else Option.Some((last + backoff))))
}

lemma schedule_ensures(unsuccessful: int, last: int, backoff: int)
  requires (unsuccessful >= 0)
  requires (last >= 0)
  ensures (schedule(unsuccessful, last, backoff).attempt == nextAttempt(unsuccessful))
  ensures ((unsuccessful == 0) ==> (match schedule(unsuccessful, last, backoff).notBefore { case Some(i_) => false case None => true }))
  ensures ((unsuccessful > 0) ==> ((match schedule(unsuccessful, last, backoff).notBefore { case Some(i_) => true case None => false }) && (match schedule(unsuccessful, last, backoff).notBefore { case Some(i_value) => (i_value == (last + backoff)) case None => false })))
  ensures ((unsuccessful > 0) ==> (backoff >= 0) ==> ((match schedule(unsuccessful, last, backoff).notBefore { case Some(i_) => true case None => false }) && (match schedule(unsuccessful, last, backoff).notBefore { case Some(i_value) => (i_value >= last) case None => false })))
{
}

function removedAfter(removals: seq<int>, seq_: int): bool
  decreases |removals|
{
  if (|removals| == 0) then
    false
  else
    var head := (if ((0 <= 0) && (0 < |removals|)) then removals[0] else seq_);
    ((head > seq_) || removedAfter(removals[1..], seq_))
}

lemma removedAfter_ensures(removals: seq<int>, seq_: int)
  ensures (removedAfter(removals, seq_) <==> exists i: int :: (((0 <= i) && (i < |removals|)) && (removals[i] > seq_)))
  ensures (removedAfter(removals, seq_) ==> forall earlier: int :: ((earlier <= seq_) ==> removedAfter(removals, earlier)))
{
}

function readyToSend(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): bool
  requires (resend >= 0)
{
  var backoffOver := (!(backedOff) || (notBefore <= now));
  var windowOver := (!(wasSent) || ((sentAt + resend) <= now));
  (backoffOver && windowOver)
}

lemma readyToSend_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 0)
  ensures (readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend) <==> ((!(backedOff) || (notBefore <= now)) && (!(wasSent) || ((sentAt + resend) <= now))))
  ensures (backedOff ==> (notBefore > now) ==> !(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)))
  ensures (wasSent ==> (now < (sentAt + resend)) ==> !(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)))
{
}

function waitsUntil(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): int
  requires (resend >= 0)
{
  var backoff := (if backedOff then notBefore else now);
  if (backoff > now) then
    backoff
  else
    if wasSent then
      (sentAt + resend)
    else
      now
}

lemma waitsUntil_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 0)
  ensures ((waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) <= now) <==> readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend))
  ensures (backedOff ==> (notBefore > now) ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == notBefore))
  ensures ((!(backedOff) || (notBefore <= now)) ==> wasSent ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == (sentAt + resend)))
  ensures ((!(backedOff) || (notBefore <= now)) ==> !(wasSent) ==> (waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend) == now))
{
}

function looksAgainAt(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int): int
  requires (resend >= 1)
{
  var at := waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend);
  if (at > now) then
    at
  else
    (now + resend)
}

lemma looksAgainAt_ensures(now: int, backedOff: bool, notBefore: int, wasSent: bool, sentAt: int, resend: int)
  requires (resend >= 1)
  ensures (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) > now)
  ensures (!(readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend)) ==> (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) == waitsUntil(now, backedOff, notBefore, wasSent, sentAt, resend)))
  ensures (readyToSend(now, backedOff, notBefore, wasSent, sentAt, resend) ==> (looksAgainAt(now, backedOff, notBefore, wasSent, sentAt, resend) == (now + resend)))
{
}

function earliestAfter(now: int, times: seq<int>): Option<int>
  decreases |times|
{
  if (|times| == 0) then
    None
  else
    var head := (if ((0 <= 0) && (0 < |times|)) then times[0] else now);
    var rest := earliestAfter(now, times[1..]);
    if (head <= now) then
      rest
    else
      match rest {
        case Some(i_rest_val) =>
          Some((if (head < i_rest_val) then head else i_rest_val))
        case None =>
          Some(head)
      }
}

lemma earliestAfter_ensures(now: int, times: seq<int>)
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => (i_result_val > now) case None => true })
  ensures ((match earliestAfter(now, times) { case Some(i_) => false case None => true }) <==> forall i: int :: ((0 <= i) ==> (i < |times|) ==> (times[i] <= now)))
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => forall i: int :: ((0 <= i) ==> (i < |times|) ==> (times[i] > now) ==> (i_result_val <= times[i])) case None => true })
  ensures (match earliestAfter(now, times) { case Some(i_result_val) => exists i: int :: (((0 <= i) && (i < |times|)) && (times[i] == i_result_val)) case None => true })
{
}

function staleLease(derived: bool, seated: bool, removedAfterCause: bool): bool
{
  ((!(derived) || !(seated)) || removedAfterCause)
}

lemma staleLease_ensures(derived: bool, seated: bool, removedAfterCause: bool)
  ensures (staleLease(derived, seated, removedAfterCause) <==> ((!(derived) || !(seated)) || removedAfterCause))
  ensures (derived ==> seated ==> !(removedAfterCause) ==> !(staleLease(derived, seated, removedAfterCause)))
{
}

function endingOf(running: bool, stale: bool, pastExpiry: bool): Ending
{
  if !(running) then
    Ending.stays
  else
    if stale then
      Ending.revoked
    else
      if pastExpiry then
        Ending.expired
      else
        Ending.stays
}

lemma endingOf_ensures(running: bool, stale: bool, pastExpiry: bool)
  ensures (!(running) ==> endingOf(running, stale, pastExpiry).stays?)
  ensures (running ==> stale ==> endingOf(running, stale, pastExpiry).revoked?)
  ensures (running ==> !(stale) ==> pastExpiry ==> endingOf(running, stale, pastExpiry).expired?)
  ensures (running ==> !(stale) ==> !(pastExpiry) ==> endingOf(running, stale, pastExpiry).stays?)
  ensures (endingOf(running, stale, pastExpiry).expired? ==> !(stale))
  ensures ((!endingOf(running, stale, pastExpiry).stays?) ==> running)
{
}

function mayClose(stopped: bool, endings: int, exchangeOpen: bool, exchangeLive: bool): bool
  requires (endings >= 0)
{
  (((!(stopped) && (endings == 0)) && exchangeOpen) && !(exchangeLive))
}

lemma mayClose_ensures(stopped: bool, endings: int, exchangeOpen: bool, exchangeLive: bool)
  requires (endings >= 0)
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> !(stopped))
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> (endings == 0))
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> exchangeOpen)
  ensures (mayClose(stopped, endings, exchangeOpen, exchangeLive) ==> !(exchangeLive))
  ensures (!(stopped) ==> (endings == 0) ==> exchangeOpen ==> !(exchangeLive) ==> mayClose(stopped, endings, exchangeOpen, exchangeLive))
{
}

function closeMoved(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool): bool
{
  match open {
    case Some(i_open_val) =>
      ((i_open_val.from == close.from) && ((lastSeq != close.through) || exchangeLive))
    case None =>
      false
  }
}

lemma closeMoved_ensures(open: Option<OpenExchange>, close: CloseRef, lastSeq: int, exchangeLive: bool)
  ensures (closeMoved(open, close, lastSeq, exchangeLive) ==> (match open { case Some(i_) => true case None => false }))
  ensures (match open { case Some(i_open_val) => (closeMoved(open, close, lastSeq, exchangeLive) <==> ((i_open_val.from == close.from) && ((lastSeq != close.through) || exchangeLive))) case None => true })
  ensures (closeMoved(open, close, lastSeq, exchangeLive) ==> !(admitsClose(open, close, lastSeq, exchangeLive)))
  ensures (admitsClose(open, close, lastSeq, exchangeLive) ==> !(closeMoved(open, close, lastSeq, exchangeLive)))
{
}

function namesWriter(configured: bool, seated: bool): bool
{
  (configured && seated)
}

lemma namesWriter_ensures(configured: bool, seated: bool)
  ensures (namesWriter(configured, seated) ==> configured)
  ensures (namesWriter(configured, seated) ==> seated)
  ensures (configured ==> seated ==> namesWriter(configured, seated))
{
}

function holdsExchange(source: Source): bool
{
  source.message?
}

lemma holdsExchange_ensures(source: Source)
  ensures (holdsExchange(source) <==> source.message?)
{
}

function exchangeLive(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int): bool
{
  ((exists lease :: lease in leases && (isLive(lease.phase, lease.expiresAt, now) && holdsExchange(lease.source))) || (exists owed :: owed in due && holdsExchange(owed.source)))
}

lemma exchangeLive_ensures(leases: seq<LiveLease>, due: seq<OwedActivation>, now: int)
  ensures (exchangeLive(leases, due, now) <==> ((exists i: int :: ((((0 <= i) && (i < |leases|)) && isLive(leases[i].phase, leases[i].expiresAt, now)) && holdsExchange(leases[i].source))) || exists j: int :: (((0 <= j) && (j < |due|)) && holdsExchange(due[j].source))))
  ensures ((forall i: int :: ((0 <= i) ==> (i < |leases|) ==> leases[i].source.closed?)) ==> (forall j: int :: ((0 <= j) ==> (j < |due|) ==> due[j].source.closed?)) ==> !(exchangeLive(leases, due, now)))
  ensures ((exists j: int :: (((0 <= j) && (j < |due|)) && due[j].source.message?)) ==> exchangeLive(leases, due, now))
  ensures ((forall i: int :: ((0 <= i) ==> (i < |leases|) ==> !(isLive(leases[i].phase, leases[i].expiresAt, now)))) ==> (|due| == 0) ==> !(exchangeLive(leases, due, now)))
  ensures ((|leases| == 0) ==> (|due| == 0) ==> !(exchangeLive(leases, due, now)))
{
}

function wellFormed(id: ActivationFields): bool
{
  (((id.position >= 1) && (id.attempt >= 1)) && (|id.seat| >= 1))
}

lemma wellFormed_ensures(id: ActivationFields)
  ensures (wellFormed(id) <==> (((id.position >= 1) && (id.attempt >= 1)) && (|id.seat| >= 1)))
{
}

function nextActivationId(source: Source, position: int, seat: string, unsuccessfulAttempts: int): ActivationFields
  requires (position >= 1)
  requires (|seat| >= 1)
  requires (unsuccessfulAttempts >= 0)
{
  ActivationFields(source, position, seat, nextAttempt(unsuccessfulAttempts))
}

lemma nextActivationId_ensures(source: Source, position: int, seat: string, unsuccessfulAttempts: int)
  requires (position >= 1)
  requires (|seat| >= 1)
  requires (unsuccessfulAttempts >= 0)
  ensures (nextActivationId(source, position, seat, unsuccessfulAttempts).source == source)
  ensures (nextActivationId(source, position, seat, unsuccessfulAttempts).position == position)
  ensures (nextActivationId(source, position, seat, unsuccessfulAttempts).seat == seat)
  ensures (nextActivationId(source, position, seat, unsuccessfulAttempts).attempt == nextAttempt(unsuccessfulAttempts))
  ensures (nextActivationId(source, position, seat, unsuccessfulAttempts).attempt == (unsuccessfulAttempts + 1))
  ensures wellFormed(nextActivationId(source, position, seat, unsuccessfulAttempts))
{
}

function names(summary: Option<string>, writer: string): bool
{
  match summary {
    case Some(i_summary_val) =>
      (i_summary_val == writer)
    case None =>
      false
  }
}

lemma names_ensures(summary: Option<string>, writer: string)
  ensures ((match summary { case Some(i_) => false case None => true }) ==> !(names(summary, writer)))
  ensures (match summary { case Some(i_summary_val) => (names(summary, writer) <==> (i_summary_val == writer)) case None => true })
{
}

function closeMatches(close: CloseFact, through: int, writer: string): bool
{
  ((close.through == through) && names(close.summary, writer))
}

lemma closeMatches_ensures(close: CloseFact, through: int, writer: string)
  ensures (closeMatches(close, through, writer) <==> ((close.through == through) && names(close.summary, writer)))
{
}

function closeFor(closes: seq<CloseFact>, through: int, writer: string): Option<CloseFact>
{
  SeqFind(closes, (close: CloseFact) => closeMatches(close, through, writer))
}

lemma closeFor_ensures(closes: seq<CloseFact>, through: int, writer: string)
  ensures (match closeFor(closes, through, writer) { case Some(i_result_val) => closeMatches(i_result_val, through, writer) case None => true })
  ensures (match closeFor(closes, through, writer) { case Some(i_result_val) => exists j: int :: ((((0 <= j) && (j < |closes|)) && (closes[j] == i_result_val)) && forall k: int :: ((0 <= k) ==> (k < j) ==> !(closeMatches(closes[k], through, writer)))) case None => true })
  ensures ((match closeFor(closes, through, writer) { case Some(i_) => false case None => true }) ==> forall j: int :: ((0 <= j) ==> (j < |closes|) ==> !(closeMatches(closes[j], through, writer))))
{
}

function activationGrant(id: ActivationFields, cancelledAt: Option<int>, seated: bool, removed: bool, recorded: bool, close: Option<CloseFact>): Option<Grant>
  requires wellFormed(id)
  requires (match close { case Some(i_close_val) => closeMatches(i_close_val, id.position, id.seat) case None => true })
{
  if !(survivesCancellation(id.position, cancelledAt)) then
    None
  else
    if !(seated) then
      None
    else
      if removed then
        None
      else
        if id.source.message? then
          if !(recorded) then
            None
          else
            Some(Grant(id.seat, id.attempt, GrantPurpose.respond(id.position)))
        else
          match close {
            case Some(i_close_val) =>
              Some(Grant(id.seat, id.attempt, GrantPurpose.summarize(i_close_val.from, i_close_val.owner, i_close_val.through)))
            case None =>
              None
          }
}

lemma activationGrant_ensures(id: ActivationFields, cancelledAt: Option<int>, seated: bool, removed: bool, recorded: bool, close: Option<CloseFact>)
  requires wellFormed(id)
  requires (match close { case Some(i_close_val) => closeMatches(i_close_val, id.position, id.seat) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => ((i_result_val.seat == id.seat) && (i_result_val.attempt == id.attempt)) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => survivesCancellation(id.position, cancelledAt) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => (match cancelledAt { case Some(i_cancelledAt_val) => !(beforeCancellation(id.position, i_cancelledAt_val)) case None => true }) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => seated case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => !(removed) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => (i_result_val.purpose.respond? <==> id.source.message?) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => (id.source.message? ==> (recorded && (i_result_val.purpose.message == id.position))) case None => true })
  ensures (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => (id.source.closed? ==> ((match close { case Some(i_) => true case None => false }) && (i_result_val.purpose.through == id.position))) case None => true })
  ensures (match close { case Some(i_close_val) => (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_result_val) => (id.source.closed? ==> (((i_result_val.purpose.exchange == i_close_val.from) && (i_result_val.purpose.person == i_close_val.owner)) && (i_result_val.purpose.through == i_close_val.through))) case None => true }) case None => true })
  ensures (id.source.message? ==> recorded ==> survivesCancellation(id.position, cancelledAt) ==> seated ==> !(removed) ==> (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_) => true case None => false }))
  ensures (match close { case Some(i_close_val) => (id.source.closed? ==> survivesCancellation(id.position, cancelledAt) ==> seated ==> !(removed) ==> (match activationGrant(id, cancelledAt, seated, removed, recorded, close) { case Some(i_) => true case None => false })) case None => true })
{
}

function stoodDown(drafts: seq<Draft>): bool
{
  (exists draft :: draft in drafts && (draft.ended? && ((draft.reason.released? || draft.reason.revoked?) || draft.reason.abandoned?)))
}

lemma stoodDown_ensures(drafts: seq<Draft>)
  ensures (stoodDown(drafts) <==> exists i: int :: ((((0 <= i) && (i < |drafts|)) && drafts[i].ended?) && ((drafts[i].reason.released? || drafts[i].reason.revoked?) || drafts[i].reason.abandoned?)))
  ensures (stoodDown(drafts) ==> (|drafts| > 0))
{
}

function draftReleased(drafts: seq<Draft>): bool
{
  (exists draft :: draft in drafts && (draft.ended? && draft.reason.released?))
}

lemma draftReleased_ensures(drafts: seq<Draft>)
  ensures (draftReleased(drafts) <==> exists i: int :: ((((0 <= i) && (i < |drafts|)) && drafts[i].ended?) && drafts[i].reason.released?))
  ensures (draftReleased(drafts) ==> stoodDown(drafts))
{
}

function draftRunning(drafts: seq<Draft>): bool
{
  (exists draft :: draft in drafts && draft.running?)
}

lemma draftRunning_ensures(drafts: seq<Draft>)
  ensures (draftRunning(drafts) <==> exists i: int :: (((0 <= i) && (i < |drafts|)) && drafts[i].running?))
{
}

function cancelledDraft(drafts: seq<Draft>, cancelledAfterClose: bool): bool
{
  (cancelledAfterClose && (exists draft :: draft in drafts && ((draft.ended? && draft.reason.revoked?) && draft.cancelled)))
}

lemma cancelledDraft_ensures(drafts: seq<Draft>, cancelledAfterClose: bool)
  ensures (cancelledDraft(drafts, cancelledAfterClose) ==> cancelledAfterClose)
  ensures (cancelledDraft(drafts, cancelledAfterClose) ==> stoodDown(drafts))
  ensures (cancelledDraft(drafts, cancelledAfterClose) <==> (cancelledAfterClose && exists i: int :: (((((0 <= i) && (i < |drafts|)) && drafts[i].ended?) && drafts[i].reason.revoked?) && drafts[i].cancelled)))
{
}

function summaryVerdict(covered: bool, writerNamed: bool, removedAfterClose: bool, drafts: seq<Draft>, cancelledAfterClose: bool): Verdict
{
  if covered then
    Verdict.published
  else
    if !(writerNamed) then
      Verdict.silent
    else
      if removedAfterClose then
        Verdict.failed
      else
        var down := stoodDown(drafts);
        if cancelledDraft(drafts, cancelledAfterClose) then
          Verdict.failed
        else
          if (!(down) && cancelledAfterClose) then
            Verdict.failed
          else
            if !(down) then
              pending(true)
            else
              if draftRunning(drafts) then
                pending(false)
              else
                if draftReleased(drafts) then
                  Verdict.silent
                else
                  Verdict.failed
}

lemma summaryVerdict_ensures(covered: bool, writerNamed: bool, removedAfterClose: bool, drafts: seq<Draft>, cancelledAfterClose: bool)
  ensures (covered ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).published?)
  ensures (summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).published? ==> covered)
  ensures (!(covered) ==> !(writerNamed) ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).silent?)
  ensures (!(covered) ==> writerNamed ==> removedAfterClose ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).failed?)
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> !(stoodDown(drafts)) ==> !(cancelledAfterClose) ==> (summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).pending? && summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).owed))
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> !(stoodDown(drafts)) ==> cancelledAfterClose ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).failed?)
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> cancelledDraft(drafts, cancelledAfterClose) ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).failed?)
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> stoodDown(drafts) ==> !(cancelledDraft(drafts, cancelledAfterClose)) ==> draftRunning(drafts) ==> (summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).pending? && !(summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).owed)))
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> stoodDown(drafts) ==> !(cancelledDraft(drafts, cancelledAfterClose)) ==> !(draftRunning(drafts)) ==> draftReleased(drafts) ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).silent?)
  ensures (!(covered) ==> writerNamed ==> !(removedAfterClose) ==> stoodDown(drafts) ==> !(cancelledDraft(drafts, cancelledAfterClose)) ==> !(draftRunning(drafts)) ==> !(draftReleased(drafts)) ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).failed?)
  ensures ((summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).pending? && summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).owed) <==> ((((!(covered) && writerNamed) && !(removedAfterClose)) && !(stoodDown(drafts))) && !(cancelledAfterClose)))
  ensures (cancelledAfterClose ==> summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).pending? ==> !(summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).owed))
  ensures (summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).pending? ==> !(summaryVerdict(covered, writerNamed, removedAfterClose, drafts, cancelledAfterClose).owed) ==> (|drafts| > 0))
{
}

function inside(range: Range, seq_: int): bool
{
  ((range.from <= seq_) && (seq_ <= range.through))
}

lemma inside_ensures(range: Range, seq_: int)
  ensures (inside(range, seq_) <==> ((range.from <= seq_) && (seq_ <= range.through)))
{
}

function admitsLease(kind: LeaseKind, known: Option<LeasePhase>, live: bool, owed: bool, seatHeld: bool): Admission
  requires ((match known { case Some(i_) => false case None => true }) ==> !(live))
  requires (match known { case Some(i_known_val) => (i_known_val.ended? ==> !(live)) case None => true })
{
  if ((match known { case Some(i_) => false case None => true }) && (kind.renew? || !(owed))) then
    Admission.ended
  else
    if ((match known { case Some(i_) => false case None => true }) && seatHeld) then
      Admission.held
    else
      match known {
        case Some(i_known_val) =>
          if !(live) then
            Admission.ended
          else
            Admission.granted
        case None =>
          Admission.granted
      }
}

lemma admitsLease_ensures(kind: LeaseKind, known: Option<LeasePhase>, live: bool, owed: bool, seatHeld: bool)
  requires ((match known { case Some(i_) => false case None => true }) ==> !(live))
  requires (match known { case Some(i_known_val) => (i_known_val.ended? ==> !(live)) case None => true })
  ensures (admitsLease(kind, known, live, owed, seatHeld).granted? ==> ((((kind.claim? && (match known { case Some(i_) => false case None => true })) && owed) && !(seatHeld)) || live))
  ensures (live ==> admitsLease(kind, known, live, owed, seatHeld).granted?)
  ensures (kind.renew? ==> (match known { case Some(i_) => false case None => true }) ==> admitsLease(kind, known, live, owed, seatHeld).ended?)
  ensures (match known { case Some(i_known_val) => (!(live) ==> admitsLease(kind, known, live, owed, seatHeld).ended?) case None => true })
  ensures ((match known { case Some(i_) => false case None => true }) ==> !(owed) ==> admitsLease(kind, known, live, owed, seatHeld).ended?)
  ensures (kind.claim? ==> (match known { case Some(i_) => false case None => true }) ==> owed ==> seatHeld ==> admitsLease(kind, known, live, owed, seatHeld).held?)
  ensures (kind.claim? ==> (match known { case Some(i_) => false case None => true }) ==> owed ==> !(seatHeld) ==> admitsLease(kind, known, live, owed, seatHeld).granted?)
  ensures (match known { case Some(i_known_val) => (!admitsLease(kind, known, live, owed, seatHeld).held?) case None => true })
  ensures (admitsLease(kind, known, live, owed, seatHeld).held? ==> ((match known { case Some(i_) => false case None => true }) && seatHeld))
{
}

function stampedSummary(owner: string, from: int, through: int): Stamped
{
  Stamped(owner, Range(from, through))
}

lemma stampedSummary_ensures(owner: string, from: int, through: int)
  ensures (stampedSummary(owner, from, through).to == owner)
  ensures (stampedSummary(owner, from, through).covers.from == from)
  ensures (stampedSummary(owner, from, through).covers.through == through)
  ensures coversExchange(stampedSummary(owner, from, through).to, stampedSummary(owner, from, through).covers.from, stampedSummary(owner, from, through).covers.through, owner, from, through)
{
}

function addressesOwner(to: Option<string>, owner: string): bool
{
  match to {
    case Some(i_to_val) =>
      (i_to_val == owner)
    case None =>
      true
  }
}

lemma addressesOwner_ensures(to: Option<string>, owner: string)
  ensures ((match to { case Some(i_) => false case None => true }) ==> addressesOwner(to, owner))
  ensures (match to { case Some(i_to_val) => (addressesOwner(to, owner) <==> (i_to_val == owner)) case None => true })
{
}

function presenceOutcome(kind: PresenceKind, agentName: bool, present: bool, sameIdentity: bool): Outcome
{
  if kind.arrived? then
    if agentName then
      Outcome.refused
    else
      if present then
        if sameIdentity then
          Outcome.unchanged_
        else
          Outcome.refused
      else
        Outcome.written
  else
    if present then
      Outcome.written
    else
      Outcome.unchanged_
}

lemma presenceOutcome_ensures(kind: PresenceKind, agentName: bool, present: bool, sameIdentity: bool)
  ensures (kind.arrived? ==> agentName ==> presenceOutcome(kind, agentName, present, sameIdentity).refused?)
  ensures (kind.arrived? ==> !(agentName) ==> present ==> !(sameIdentity) ==> presenceOutcome(kind, agentName, present, sameIdentity).refused?)
  ensures (kind.arrived? ==> !(agentName) ==> present ==> sameIdentity ==> presenceOutcome(kind, agentName, present, sameIdentity).unchanged_?)
  ensures (kind.arrived? ==> !(agentName) ==> !(present) ==> presenceOutcome(kind, agentName, present, sameIdentity).written?)
  ensures (kind.left? ==> (!presenceOutcome(kind, agentName, present, sameIdentity).refused?))
  ensures (kind.left? ==> (presenceOutcome(kind, agentName, present, sameIdentity).written? <==> present))
  ensures (presenceOutcome(kind, agentName, present, sameIdentity).written? ==> (!(agentName) || kind.left?))
  ensures (kind.arrived? ==> (presenceOutcome(kind, agentName, present, sameIdentity).written? <==> (!(agentName) && !(present))))
{
}

function membershipOutcome(kind: MembershipKind, onRoster: bool, inReserve: bool): Outcome
  requires !((onRoster && inReserve))
{
  if kind.seated? then
    if onRoster then
      Outcome.unchanged_
    else
      if inReserve then
        Outcome.written
      else
        Outcome.refused
  else
    if onRoster then
      Outcome.written
    else
      if inReserve then
        Outcome.unchanged_
      else
        Outcome.refused
}

lemma membershipOutcome_ensures(kind: MembershipKind, onRoster: bool, inReserve: bool)
  requires !((onRoster && inReserve))
  ensures (kind.seated? ==> (membershipOutcome(kind, onRoster, inReserve).unchanged_? <==> onRoster))
  ensures (kind.seated? ==> (membershipOutcome(kind, onRoster, inReserve).written? <==> inReserve))
  ensures (kind.unseated? ==> (membershipOutcome(kind, onRoster, inReserve).written? <==> onRoster))
  ensures (kind.unseated? ==> (membershipOutcome(kind, onRoster, inReserve).unchanged_? <==> inReserve))
  ensures (!(onRoster) ==> !(inReserve) ==> membershipOutcome(kind, onRoster, inReserve).refused?)
  ensures (membershipOutcome(kind, onRoster, inReserve).refused? <==> (!(onRoster) && !(inReserve)))
{
}

function hostMembership(kind: MembershipKind, onRoster: bool, isPerson: bool): bool
{
  if kind.seated? then
    (!(onRoster) && !(isPerson))
  else
    onRoster
}

lemma hostMembership_ensures(kind: MembershipKind, onRoster: bool, isPerson: bool)
  ensures (kind.seated? ==> (hostMembership(kind, onRoster, isPerson) <==> (!(onRoster) && !(isPerson))))
  ensures (kind.unseated? ==> (hostMembership(kind, onRoster, isPerson) <==> onRoster))
  ensures (isPerson ==> kind.seated? ==> !(hostMembership(kind, onRoster, isPerson)))
{
}

function commitAuthority(known: Option<LeasePhase>, pastExpiry: bool, granted: bool): Authority
{
  match known {
    case Some(i_known_val) =>
      if i_known_val.ended? then
        Authority.stale
      else
        if pastExpiry then
          Authority.stale
        else
          if granted then
            Authority.granted
          else
            Authority.refused
    case None =>
      Authority.stale
  }
}

lemma commitAuthority_ensures(known: Option<LeasePhase>, pastExpiry: bool, granted: bool)
  ensures ((match known { case Some(i_) => false case None => true }) ==> commitAuthority(known, pastExpiry, granted).stale?)
  ensures (match known { case Some(i_known_val) => (i_known_val.ended? ==> commitAuthority(known, pastExpiry, granted).stale?) case None => true })
  ensures (pastExpiry ==> commitAuthority(known, pastExpiry, granted).stale?)
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> !(pastExpiry) ==> (commitAuthority(known, pastExpiry, granted).granted? <==> granted)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> !(pastExpiry) ==> (commitAuthority(known, pastExpiry, granted).refused? <==> !(granted))) case None => true })
  ensures (commitAuthority(known, pastExpiry, granted).granted? ==> (((match known { case Some(i_) => true case None => false }) && !(pastExpiry)) && granted))
  ensures (commitAuthority(known, pastExpiry, granted).refused? ==> (((match known { case Some(i_) => true case None => false }) && !(pastExpiry)) && !(granted)))
  ensures ((!commitAuthority(known, pastExpiry, granted).stale?) ==> ((match known { case Some(i_) => true case None => false }) && !(pastExpiry)))
{
}

method latest(times: seq<int>, floor: int) returns (res: int)
  requires (floor >= 0)
  ensures (res >= floor)
  ensures forall i: int :: ((0 <= i) ==> (i < |times|) ==> (res >= times[i]))
{
  var best := floor;
  var i := 0;
  while (i < |times|)
    invariant (0 <= i)
    invariant (i <= |times|)
    invariant (best >= floor)
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> (best >= times[k]))
  {
    var v := (if ((0 <= i) && (i < |times|)) then times[i] else floor);
    if (v > best) {
      best := v;
    }
    i := (i + 1);
  }
  return best;
}

method forgets(sentIds: seq<string>, dueIds: seq<string>) returns (res: seq<string>)
  ensures (|res| <= |sentIds|)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> !((res[i] in dueIds)))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in sentIds))
  ensures forall i: int :: ((0 <= i) ==> (i < |sentIds|) ==> !((sentIds[i] in dueIds)) ==> (sentIds[i] in res))
  ensures forall i: int :: ((0 <= i) ==> (i < |dueIds|) ==> !((dueIds[i] in res)))
{
  var out: seq<string> := [];
  var i := 0;
  while (i < |sentIds|)
    invariant (0 <= i)
    invariant (i <= |sentIds|)
    invariant (|out| <= i)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> !((out[k] in dueIds)))
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] in sentIds))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> !((sentIds[k] in dueIds)) ==> (sentIds[k] in out))
    decreases (|sentIds| - i)
  {
    var id := (if ((0 <= i) && (i < |sentIds|)) then sentIds[i] else "");
    if !((id in dueIds)) {
      out := (out + [id]);
    }
    i := (i + 1);
  }
  return out;
}

method exchangeContaining(closes: seq<Range>, open: Option<int>, seq_: int) returns (res: Found)
  ensures (match res { case closed(i_result_from) => exists i: int :: (((((0 <= i) && (i < |closes|)) && inside(closes[i], seq_)) && (closes[i].from == i_result_from)) && forall k: int :: ((0 <= k) ==> (k < i) ==> !(inside(closes[k], seq_)))) case _ => true })
  ensures ((!res.closed?) ==> forall i: int :: ((0 <= i) ==> (i < |closes|) ==> !(inside(closes[i], seq_))))
  ensures ((match open { case Some(i_) => false case None => true }) ==> (!res.open?))
  ensures (match open { case Some(i_open_val) => (res.open? ==> ((i_open_val == res.from) && (res.from <= seq_))) case None => true })
  ensures ((match open { case Some(i_) => false case None => true }) ==> (!res.closed?) ==> res.outside?)
  ensures (match open { case Some(i_open_val) => (res.outside? ==> (i_open_val > seq_)) case None => true })
  ensures (match open { case Some(i_open_val) => ((i_open_val <= seq_) ==> (!res.outside?)) case None => true })
  ensures ((res.closed? || res.open?) ==> (res.from <= seq_))
{
  var i := 0;
  while (i < |closes|)
    invariant (0 <= i)
    invariant (i <= |closes|)
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> !(inside(closes[k], seq_)))
  {
    var close := (if ((0 <= i) && (i < |closes|)) then closes[i] else Range(0, -1));
    var i_t0 := inside(close, seq_);
    if i_t0 {
      return Found.closed(close.from);
    }
    i := (i + 1);
  }
  match open {
    case Some(i_open_val) =>
      if (i_open_val <= seq_) {
        return Found.open(i_open_val);
      }
    case None =>

  }
  return Found.outside;
}

method distinct(names: seq<string>) returns (res: bool)
  ensures (res <==> forall i: int :: ((0 <= i) ==> (i < |names|) ==> forall j: int :: ((0 <= j) ==> (j < i) ==> (names[i] != names[j]))))
{
  var i := 0;
  while (i < |names|)
    invariant (0 <= i)
    invariant (i <= |names|)
    invariant forall a: int :: ((0 <= a) ==> (a < i) ==> forall b: int :: ((0 <= b) ==> (b < a) ==> (names[a] != names[b])))
  {
    var j := 0;
    while (j < i)
      invariant (0 <= j)
      invariant (j <= i)
      invariant forall b: int :: ((0 <= b) ==> (b < j) ==> (names[i] != names[b]))
    {
      if (names[i] == names[j]) {
        return false;
      }
      j := (j + 1);
    }
    i := (i + 1);
  }
  return true;
}
