// Generated by lsc from rules.record.verified.ts

datatype Option<T> = None | Some(value: T)

function SeqFind<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFind(s, p).Some? ==> p(SeqFind(s, p).value)
  ensures SeqFind(s, p).Some? ==> SeqFind(s, p).value in s
  ensures SeqFind(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFind(s, p).value && p(s[i]) &&
                     (forall j: nat :: j < i ==> !p(s[j]))
  ensures SeqFind(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[0]) then Some(s[0])
  else SeqFind(s[1..], p)
}

datatype Message = Message(kind: string, seq_: int, from: string, at: string)

datatype MessageKind = said | arrived | left | seated | unseated | summary

datatype Recorded = Recorded(kind: MessageKind, from: Option<string>, to: Option<string>, text: string, subject: Option<string>, activationId: Option<string>)

datatype Contribution = said(text: string) | seated(name: string) | unseated(name: string)

function lastOf(seqs: seq<int>): int
  requires forall i: int, j: int :: ((0 <= i) ==> (i < j) ==> (j < |seqs|) ==> (seqs[i] <= seqs[j]))
  requires forall i: int :: ((0 <= i) ==> (i < |seqs|) ==> (seqs[i] >= 1))
{
  if ((0 <= (|seqs| - 1)) && ((|seqs| - 1) < |seqs|)) then
    seqs[(|seqs| - 1)]
  else
    0
}

lemma lastOf_ensures(seqs: seq<int>)
  requires forall i: int, j: int :: ((0 <= i) ==> (i < j) ==> (j < |seqs|) ==> (seqs[i] <= seqs[j]))
  requires forall i: int :: ((0 <= i) ==> (i < |seqs|) ==> (seqs[i] >= 1))
  ensures (lastOf(seqs) >= 0)
  ensures ((|seqs| == 0) ==> (lastOf(seqs) == 0))
  ensures ((|seqs| > 0) ==> (lastOf(seqs) == seqs[(|seqs| - 1)]))
  ensures forall i: int :: ((0 <= i) ==> (i < |seqs|) ==> (seqs[i] <= lastOf(seqs)))
{
}

function opensExchange(message: Message, people: seq<string>, closedThrough: int): bool
{
  (((message.kind == "said") && (message.from in people)) && (message.seq_ > closedThrough))
}

lemma opensExchange_ensures(message: Message, people: seq<string>, closedThrough: int)
  ensures (opensExchange(message, people, closedThrough) <==> (((message.kind == "said") && (message.from in people)) && (message.seq_ > closedThrough)))
  ensures ((message.kind != "said") ==> !(opensExchange(message, people, closedThrough)))
  ensures ((message.seq_ <= closedThrough) ==> !(opensExchange(message, people, closedThrough)))
{
}

function openingQuestion(messages: seq<Message>, people: seq<string>, closedThrough: int): Option<Message>
  requires forall i: int, j: int :: ((0 <= i) ==> (i < j) ==> (j < |messages|) ==> (messages[i].seq_ < messages[j].seq_))
{
  SeqFind(messages, (message: Message) => opensExchange(message, people, closedThrough))
}

lemma openingQuestion_ensures(messages: seq<Message>, people: seq<string>, closedThrough: int)
  requires forall i: int, j: int :: ((0 <= i) ==> (i < j) ==> (j < |messages|) ==> (messages[i].seq_ < messages[j].seq_))
  ensures (match openingQuestion(messages, people, closedThrough) { case Some(i_result_val) => (((i_result_val.kind == "said") && (i_result_val.from in people)) && (i_result_val.seq_ > closedThrough)) case None => true })
  ensures ((match openingQuestion(messages, people, closedThrough) { case Some(i_) => false case None => true }) <==> !(exists i: int :: (((0 <= i) && (i < |messages|)) && opensExchange(messages[i], people, closedThrough))))
  ensures (match openingQuestion(messages, people, closedThrough) { case Some(i_result_val) => exists i: int :: ((((0 <= i) && (i < |messages|)) && (messages[i] == i_result_val)) && forall j: int :: ((0 <= j) ==> (j < i) ==> !(opensExchange(messages[j], people, closedThrough)))) case None => true })
  ensures (match openingQuestion(messages, people, closedThrough) { case Some(i_result_val) => ((|messages| > 0) && (i_result_val.seq_ <= messages[(|messages| - 1)].seq_)) case None => true })
{
}

function sameName(a: Option<string>, b: Option<string>): bool
{
  match a {
    case Some(i_a_val) =>
      match b {
        case Some(i_b_val) =>
          (i_a_val == i_b_val)
        case None =>
          false
      }
    case None =>
      match b {
        case Some(i_) =>
          false
        case None =>
          true
      }
  }
}

lemma sameName_ensures(a: Option<string>, b: Option<string>)
  ensures ((match a { case Some(i_) => false case None => true }) ==> (match b { case Some(i_) => false case None => true }) ==> sameName(a, b))
  ensures (match b { case Some(i_b_val) => ((match a { case Some(i_) => false case None => true }) ==> !(sameName(a, b))) case None => true })
  ensures (match a { case Some(i_a_val) => ((match b { case Some(i_) => false case None => true }) ==> !(sameName(a, b))) case None => true })
  ensures (match a { case Some(i_a_val) => (match b { case Some(i_b_val) => (sameName(a, b) <==> (i_a_val == i_b_val)) case None => true }) case None => true })
{
}

function namedAs(optional: Option<string>, name: string): bool
{
  match optional {
    case Some(i_optional_val) =>
      (i_optional_val == name)
    case None =>
      false
  }
}

lemma namedAs_ensures(optional: Option<string>, name: string)
  ensures ((match optional { case Some(i_) => false case None => true }) ==> !(namedAs(optional, name)))
  ensures (match optional { case Some(i_optional_val) => (namedAs(optional, name) <==> (i_optional_val == name)) case None => true })
{
}

function deliveryMatches(from: string, to: Option<string>, text: string, message: Recorded): bool
{
  if (!message.kind.said?) then
    false
  else
    match message.activationId {
      case Some(i_message_activationId_val) =>
        false
      case None =>
        if !(namedAs(message.from, from)) then
          false
        else
          (sameName(message.to, to) && (message.text == text))
    }
}

lemma deliveryMatches_ensures(from: string, to: Option<string>, text: string, message: Recorded)
  ensures (deliveryMatches(from, to, text, message) <==> ((((message.kind.said? && (match message.activationId { case Some(i_) => false case None => true })) && namedAs(message.from, from)) && sameName(message.to, to)) && (message.text == text)))
  ensures (deliveryMatches(from, to, text, message) ==> message.kind.said?)
  ensures (deliveryMatches(from, to, text, message) ==> (match message.activationId { case Some(i_) => false case None => true }))
  ensures (match message.activationId { case Some(i_message_activationId_val) => !(deliveryMatches(from, to, text, message)) case None => true })
{
}

function sameMembership(kind: MessageKind, subject: Option<string>, intentKind: MessageKind, name: string): bool
{
  ((kind == intentKind) && namedAs(subject, name))
}

lemma sameMembership_ensures(kind: MessageKind, subject: Option<string>, intentKind: MessageKind, name: string)
  ensures (sameMembership(kind, subject, intentKind, name) <==> ((kind == intentKind) && namedAs(subject, name)))
{
}

function contributionMatches(activation: string, seat: string, intent: Contribution, to: Option<string>, message: Recorded): bool
{
  if !(namedAs(message.activationId, activation)) then
    false
  else
    if !(namedAs(message.from, seat)) then
      false
    else
      match intent {
        case seated(i_intent_name) =>
          sameMembership(message.kind, message.subject, MessageKind.seated, i_intent_name)
        case unseated(i_intent_name) =>
          sameMembership(message.kind, message.subject, MessageKind.unseated, i_intent_name)
        case said(i_intent_text) =>
          if message.kind.said? then
            (sameName(message.to, to) && (message.text == i_intent_text))
          else
            if (!message.kind.summary?) then
              false
            else
              match to {
                case Some(i_to_val) =>
                  if !(namedAs(message.to, i_to_val)) then
                    false
                  else
                    (message.text == i_intent_text)
                case None =>
                  (message.text == i_intent_text)
              }
      }
}

lemma contributionMatches_ensures(activation: string, seat: string, intent: Contribution, to: Option<string>, message: Recorded)
  ensures (contributionMatches(activation, seat, intent, to, message) ==> namedAs(message.activationId, activation))
  ensures (contributionMatches(activation, seat, intent, to, message) ==> namedAs(message.from, seat))
  ensures ((match message.activationId { case Some(i_) => false case None => true }) ==> !(contributionMatches(activation, seat, intent, to, message)))
  ensures ((message.kind.arrived? || message.kind.left?) ==> !(contributionMatches(activation, seat, intent, to, message)))
  ensures (intent.seated? ==> (contributionMatches(activation, seat, intent, to, message) <==> (((namedAs(message.activationId, activation) && namedAs(message.from, seat)) && message.kind.seated?) && namedAs(message.subject, intent.name))))
  ensures (intent.unseated? ==> (contributionMatches(activation, seat, intent, to, message) <==> (((namedAs(message.activationId, activation) && namedAs(message.from, seat)) && message.kind.unseated?) && namedAs(message.subject, intent.name))))
  ensures (intent.said? ==> message.kind.said? ==> (contributionMatches(activation, seat, intent, to, message) <==> (((namedAs(message.activationId, activation) && namedAs(message.from, seat)) && sameName(message.to, to)) && (message.text == intent.text))))
  ensures (intent.said? ==> message.kind.summary? ==> (match to { case Some(i_) => false case None => true }) ==> (contributionMatches(activation, seat, intent, to, message) <==> ((namedAs(message.activationId, activation) && namedAs(message.from, seat)) && (message.text == intent.text))))
  ensures (match to { case Some(i_to_val) => (intent.said? ==> message.kind.summary? ==> (contributionMatches(activation, seat, intent, to, message) <==> (((namedAs(message.activationId, activation) && namedAs(message.from, seat)) && namedAs(message.to, i_to_val)) && (message.text == intent.text)))) case None => true })
  ensures (intent.said? ==> (!message.kind.said?) ==> (!message.kind.summary?) ==> !(contributionMatches(activation, seat, intent, to, message)))
  ensures (contributionMatches(activation, seat, intent, to, message) ==> intent.said? ==> (message.text == intent.text))
{
}

method discussion(messages: seq<Message>, from: int, through: int) returns (res: seq<Message>)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (((res[i].kind != "summary") && (from <= res[i].seq_)) && (res[i].seq_ <= through)))
  ensures forall k: int :: ((0 <= k) ==> (k < |messages|) ==> (messages[k].kind != "summary") ==> (from <= messages[k].seq_) ==> (messages[k].seq_ <= through) ==> exists i: int :: (((0 <= i) && (i < |res|)) && (res[i] == messages[k])))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in messages))
  ensures (|res| <= |messages|)
{
  var out: seq<Message> := [];
  var i := 0;
  while (i < |messages|)
    invariant (0 <= i)
    invariant (i <= |messages|)
    invariant (|out| <= i)
    invariant forall m: int :: ((0 <= m) ==> (m < |out|) ==> (((out[m].kind != "summary") && (from <= out[m].seq_)) && (out[m].seq_ <= through)))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> (messages[k].kind != "summary") ==> (from <= messages[k].seq_) ==> (messages[k].seq_ <= through) ==> exists m: int :: (((0 <= m) && (m < |out|)) && (out[m] == messages[k])))
    invariant forall m: int :: ((0 <= m) ==> (m < |out|) ==> (out[m] in messages))
  {
    var head := messages[i];
    if (((head.kind != "summary") && (head.seq_ >= from)) && (head.seq_ <= through)) {
      ghost var before: seq<Message> := out;
      out := (out + [head]);
      assert forall m: int :: ((0 <= m) ==> (m < |before|) ==> (out[m] == before[m]));
      assert (out[|before|] == head);
    }
    i := (i + 1);
  }
  return out;
}

method messagesSince(messages: seq<Message>, since: int) returns (res: seq<Message>)
  requires forall a: int, b: int :: ((0 <= a) ==> (a < b) ==> (b < |messages|) ==> (messages[a].seq_ < messages[b].seq_))
  ensures (|res| <= |messages|)
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i].seq_ > since))
  ensures forall i: int :: ((0 <= i) ==> (i < |res|) ==> (res[i] in messages))
  ensures forall k: int :: ((0 <= k) ==> (k < |messages|) ==> (messages[k].seq_ > since) ==> (messages[k] in res))
  ensures forall a: int, b: int :: ((0 <= a) ==> (a < b) ==> (b < |res|) ==> (res[a].seq_ < res[b].seq_))
{
  var out: seq<Message> := [];
  var i := 0;
  while (i < |messages|)
    invariant (0 <= i)
    invariant (i <= |messages|)
    invariant (|out| <= i)
    invariant forall m: int :: ((0 <= m) ==> (m < |out|) ==> (out[m].seq_ > since))
    invariant forall m: int :: ((0 <= m) ==> (m < |out|) ==> (out[m] in messages))
    invariant forall k: int :: ((0 <= k) ==> (k < i) ==> (messages[k].seq_ > since) ==> (messages[k] in out))
    invariant forall a: int, b: int :: ((0 <= a) ==> (a < b) ==> (b < |out|) ==> (out[a].seq_ < out[b].seq_))
    invariant forall m: int :: ((0 <= m) ==> (m < |out|) ==> forall k: int :: ((i <= k) ==> (k < |messages|) ==> (out[m].seq_ < messages[k].seq_)))
  {
    var head := messages[i];
    if (head.seq_ > since) {
      ghost var before: seq<Message> := out;
      out := (out + [head]);
      assert forall m: int :: ((0 <= m) ==> (m < |before|) ==> (out[m] == before[m]));
      assert (out[|before|] == head);
    }
    i := (i + 1);
  }
  return out;
}
