// Generated by lsc from rules.verified.ts

function expired(expiry: int, now: int): bool
{
  (expiry <= now)
}

lemma expired_ensures(expiry: int, now: int)
  ensures (expired(expiry, now) <==> (expiry <= now))
{
}

function atWork(since: int, ended: bool, until: int, seq_: int): bool
{
  ((since < seq_) && (!(ended) || (until >= seq_)))
}

lemma atWork_ensures(since: int, ended: bool, until: int, seq_: int)
  ensures (atWork(since, ended, until, seq_) ==> (since < seq_))
  ensures (atWork(since, ended, until, seq_) ==> ended ==> (until >= seq_))
  ensures (!(ended) ==> (atWork(since, ended, until, seq_) <==> (since < seq_)))
{
}

function coversAttempt(ended: bool, until: int, seq_: int): bool
{
  (!(ended) || (seq_ <= until))
}

lemma coversAttempt_ensures(ended: bool, until: int, seq_: int)
  ensures (!(ended) ==> coversAttempt(ended, until, seq_))
  ensures (ended ==> (coversAttempt(ended, until, seq_) <==> (seq_ <= until)))
{
}

function givesUp(attempts: int, cap: int): bool
  requires (attempts >= 0)
  requires (cap >= 1)
{
  (attempts >= cap)
}

lemma givesUp_ensures(attempts: int, cap: int)
  requires (attempts >= 0)
  requires (cap >= 1)
  ensures (givesUp(attempts, cap) <==> (attempts >= cap))
  ensures (!(givesUp(attempts, cap)) ==> ((attempts + 1) <= cap))
{
}

function nextAttempt(attempts: int): int
  requires (attempts >= 0)
{
  (attempts + 1)
}

lemma nextAttempt_ensures(attempts: int)
  requires (attempts >= 0)
  ensures (nextAttempt(attempts) == (attempts + 1))
  ensures (nextAttempt(attempts) >= 1)
{
}

function beforeCancellation(position: int, cancelledAt: int): bool
{
  (position < cancelledAt)
}

lemma beforeCancellation_ensures(position: int, cancelledAt: int)
  ensures (beforeCancellation(position, cancelledAt) <==> (position < cancelledAt))
{
}

function taskIdleEpoch(activity: int): int
  requires (activity >= 0)
{
  if (activity < 1) then
    1
  else
    activity
}

lemma taskIdleEpoch_ensures(activity: int)
  requires (activity >= 0)
  ensures (taskIdleEpoch(activity) >= 1)
  ensures ((activity >= 1) ==> (taskIdleEpoch(activity) == activity))
{
}

function shouldRequestTaskIdle(open: bool, quiet: bool, pendingDelivery: bool, hasSameEpoch: bool): bool
{
  (((open && quiet) && !(pendingDelivery)) && !(hasSameEpoch))
}

lemma shouldRequestTaskIdle_ensures(open: bool, quiet: bool, pendingDelivery: bool, hasSameEpoch: bool)
  ensures (shouldRequestTaskIdle(open, quiet, pendingDelivery, hasSameEpoch) <==> (((open && quiet) && !(pendingDelivery)) && !(hasSameEpoch)))
{
}

function taskCanCreate(origin: bool, exchangeOpen: bool): bool
{
  (origin && exchangeOpen)
}

lemma taskCanCreate_ensures(origin: bool, exchangeOpen: bool)
  ensures (taskCanCreate(origin, exchangeOpen) <==> (origin && exchangeOpen))
{
}

function taskCanMutate(origin: bool, owner: bool, working: bool, steering: bool): bool
{
  ((origin && owner) || (working && !(steering)))
}

lemma taskCanMutate_ensures(origin: bool, owner: bool, working: bool, steering: bool)
  ensures (taskCanMutate(origin, owner, working, steering) <==> ((origin && owner) || (working && !(steering))))
{
}

function taskCanTransition(open: bool, replay: bool): bool
{
  (open || replay)
}

lemma taskCanTransition_ensures(open: bool, replay: bool)
  ensures (taskCanTransition(open, replay) <==> (open || replay))
{
}
