// Generated by lsc from rules.verified.ts

datatype Option<T> = None | Some(value: T)

function MathMin(a: int, b: int): int { if a <= b then a else b }

function MathMax(a: int, b: int): int { if a >= b then a else b }

datatype LeasePhase = running | ended

datatype LeaseEndReason = released | failed | revoked | expired | abandoned

datatype Purpose = respond | summarize

datatype Intent = said | seated | unseated

function expired(expiry: int, now: int): bool
{
  (expiry <= now)
}

lemma expired_ensures(expiry: int, now: int)
  ensures (expired(expiry, now) <==> (expiry <= now))
{
}

function atWork(since: int, ended: bool, until: int, seq_: int): bool
{
  ((since < seq_) && (!(ended) || (until >= seq_)))
}

lemma atWork_ensures(since: int, ended: bool, until: int, seq_: int)
  ensures (atWork(since, ended, until, seq_) ==> (since < seq_))
  ensures (atWork(since, ended, until, seq_) ==> ended ==> (until >= seq_))
  ensures (!(ended) ==> (atWork(since, ended, until, seq_) <==> (since < seq_)))
{
}

function coversAttempt(ended: bool, until: int, seq_: int): bool
{
  (!(ended) || (seq_ <= until))
}

lemma coversAttempt_ensures(ended: bool, until: int, seq_: int)
  ensures (!(ended) ==> coversAttempt(ended, until, seq_))
  ensures (ended ==> (coversAttempt(ended, until, seq_) <==> (seq_ <= until)))
{
}

function givesUp(attempts: int, cap: int): bool
  requires (attempts >= 0)
  requires (cap >= 1)
{
  (attempts >= cap)
}

lemma givesUp_ensures(attempts: int, cap: int)
  requires (attempts >= 0)
  requires (cap >= 1)
  ensures (givesUp(attempts, cap) <==> (attempts >= cap))
  ensures (!(givesUp(attempts, cap)) ==> ((attempts + 1) <= cap))
{
}

function nextAttempt(attempts: int): int
  requires (attempts >= 0)
{
  (attempts + 1)
}

lemma nextAttempt_ensures(attempts: int)
  requires (attempts >= 0)
  ensures (nextAttempt(attempts) == (attempts + 1))
  ensures (nextAttempt(attempts) >= 1)
{
}

function beforeCancellation(position: int, cancelledAt: int): bool
{
  (position < cancelledAt)
}

lemma beforeCancellation_ensures(position: int, cancelledAt: int)
  ensures (beforeCancellation(position, cancelledAt) <==> (position < cancelledAt))
{
}

function mayEnd(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool): bool
{
  match known {
    case Some(i_known_val) =>
      if (i_known_val.ended? || reason.abandoned?) then
        false
      else
        (reason.revoked? || (pastExpiry == reason.expired?))
    case None =>
      (reason.revoked? || reason.abandoned?)
  }
}

lemma mayEnd_ensures(known: Option<LeasePhase>, reason: LeaseEndReason, pastExpiry: bool)
  ensures ((match known { case Some(i_) => false case None => true }) ==> (mayEnd(known, reason, pastExpiry) <==> (reason.revoked? || reason.abandoned?)))
  ensures (match known { case Some(i_known_val) => (i_known_val.ended? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.abandoned? ==> !(mayEnd(known, reason, pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.revoked? ==> mayEnd(known, reason, pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.expired? ==> (mayEnd(known, reason, pastExpiry) <==> pastExpiry)) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.released? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
  ensures (match known { case Some(i_known_val) => (i_known_val.running? ==> reason.failed? ==> (mayEnd(known, reason, pastExpiry) <==> !(pastExpiry))) case None => true })
{
}

function permits(purpose: Purpose, intent: Intent): bool
{
  match intent {
    case said =>
      (purpose.respond? || purpose.summarize?)
    case seated =>
      purpose.respond?
    case unseated =>
      purpose.respond?
  }
}

lemma permits_ensures(purpose: Purpose, intent: Intent)
  ensures (intent.said? ==> permits(purpose, intent))
  ensures ((!intent.said?) ==> (permits(purpose, intent) <==> purpose.respond?))
  ensures (purpose.summarize? ==> (permits(purpose, intent) <==> intent.said?))
  ensures (purpose.respond? ==> permits(purpose, intent))
{
}

function leaseExpiry(now: int, claimedAt: int, expiry: int, deadline: int): int
  requires (expiry >= 1)
  requires (deadline >= 1)
{
  MathMin((now + expiry), (claimedAt + deadline))
}

lemma leaseExpiry_ensures(now: int, claimedAt: int, expiry: int, deadline: int)
  requires (expiry >= 1)
  requires (deadline >= 1)
  ensures (leaseExpiry(now, claimedAt, expiry, deadline) <= (now + expiry))
  ensures (leaseExpiry(now, claimedAt, expiry, deadline) <= (claimedAt + deadline))
  ensures ((leaseExpiry(now, claimedAt, expiry, deadline) == (now + expiry)) || (leaseExpiry(now, claimedAt, expiry, deadline) == (claimedAt + deadline)))
  ensures ((leaseExpiry(now, claimedAt, expiry, deadline) > now) <==> ((claimedAt + deadline) > now))
  ensures ((claimedAt == now) ==> (leaseExpiry(now, claimedAt, expiry, deadline) > now))
  ensures (!(expired(leaseExpiry(now, claimedAt, expiry, deadline), now)) <==> !(expired((claimedAt + deadline), now)))
{
}

function acknowledged(prior: Option<int>, incoming: int): int
  requires (incoming >= 0)
  requires (match prior { case Some(i_prior_val) => (i_prior_val >= 0) case None => true })
{
  match prior {
    case Some(i_prior_val) =>
      MathMax(i_prior_val, incoming)
    case None =>
      incoming
  }
}

lemma acknowledged_ensures(prior: Option<int>, incoming: int)
  requires (incoming >= 0)
  requires (match prior { case Some(i_prior_val) => (i_prior_val >= 0) case None => true })
  ensures (match prior { case Some(i_prior_val) => (acknowledged(prior, incoming) >= i_prior_val) case None => true })
  ensures (acknowledged(prior, incoming) >= incoming)
  ensures ((match prior { case Some(i_) => false case None => true }) ==> (acknowledged(prior, incoming) == incoming))
  ensures (match prior { case Some(i_prior_val) => ((acknowledged(prior, incoming) == i_prior_val) || (acknowledged(prior, incoming) == incoming)) case None => true })
  ensures (match prior { case Some(i_prior_val) => ((incoming == 0) ==> (acknowledged(prior, incoming) == i_prior_val)) case None => true })
  ensures (acknowledged(prior, incoming) >= 0)
{
}
