// Generated by lsc from rules.verified.ts

function ownEntryAfter(readThrough: int, seq_: int, unread: int): int
  requires (seq_ >= 1)
  requires (unread >= 0)
{
  if (unread == 0) then
    readThrough
  else
    (seq_ - 1)
}

lemma ownEntryAfter_ensures(readThrough: int, seq_: int, unread: int)
  requires (seq_ >= 1)
  requires (unread >= 0)
  ensures ((unread == 0) ==> (ownEntryAfter(readThrough, seq_, unread) == readThrough))
  ensures ((unread > 0) ==> (ownEntryAfter(readThrough, seq_, unread) == (seq_ - 1)))
  ensures ((unread > 0) ==> (ownEntryAfter(readThrough, seq_, unread) < seq_))
{
}
